declare const process: {
  env: {
    NODE_ENV?: string;
    EXPO_PUBLIC_API_URL?: string;
    EXPO_PUBLIC_FIRST_LAUNCH_GUARDS_ENABLED?: string;
    EXPO_PUBLIC_MONEY_PROVIDER?: string;
    EXPO_PUBLIC_MONEY_FEATURES_VISIBLE?: string;
    EXPO_PUBLIC_WALLET_VISIBLE?: string;
    EXPO_PUBLIC_PAYOUTS_VISIBLE?: string;
    EXPO_PUBLIC_MONEY_TRADES_ENABLED?: string;
    EXPO_PUBLIC_CASH_TRADES_ENABLED?: string;
    EXPO_PUBLIC_BUSINESS_ACCOUNTS_VISIBLE?: string;
    EXPO_PUBLIC_PLANS_ENABLED?: string;
    EXPO_PUBLIC_PLANS_VISIBLE?: string;
    EXPO_PUBLIC_ADS_ENABLED?: string;
    EXPO_PUBLIC_MOBILE_ADS_ENABLED?: string;
    EXPO_PUBLIC_ADS_PROVIDER?: string;
    EXPO_PUBLIC_ADS_DEBUG_PLACEHOLDERS?: string;
    EXPO_PUBLIC_AI_ENABLED?: string;
    EXPO_PUBLIC_AI_PROVIDER?: string;
    EXPO_PUBLIC_AI_MODERATION_ENABLED?: string;
    EXPO_PUBLIC_AI_SUGGESTIONS_ENABLED?: string;
    EXPO_PUBLIC_AI_ADMIN_ASSIST_ENABLED?: string;
    EXPO_PUBLIC_AI_SAFETY_CLASSIFIER_ENABLED?: string;
    EXPO_PUBLIC_AI_DEBUG_PLACEHOLDERS?: string;
  };
};

