declare const process: {
  env: {
    NODE_ENV?: string;
    EXPO_PUBLIC_API_URL?: string;
    EXPO_PUBLIC_FIRST_LAUNCH_GUARDS_ENABLED?: string;
    EXPO_PUBLIC_MONEY_PROVIDER?: string;
    EXPO_PUBLIC_MONEY_FEATURES_VISIBLE?: string;
    EXPO_PUBLIC_WALLET_VISIBLE?: string;
    EXPO_PUBLIC_PAYOUTS_VISIBLE?: string;
    EXPO_PUBLIC_MONEY_TRADES_ENABLED?: string;
    EXPO_PUBLIC_CASH_TRADES_ENABLED?: string;
    EXPO_PUBLIC_BUSINESS_ACCOUNTS_VISIBLE?: string;
    EXPO_PUBLIC_PLANS_ENABLED?: string;
    EXPO_PUBLIC_PLANS_VISIBLE?: string;
  };
};

