import bcrypt from 'bcryptjs';
import { PrismaClient, type Prisma } from '@prisma/client';

const prisma = new PrismaClient();

const demoPassword = process.env.SEED_DEMO_PASSWORD?.trim() || 'password123';
const adminEmail = process.env.SEED_ADMIN_EMAIL?.trim() || 'admin@hellowhen.app';
const adminPassword = process.env.SEED_ADMIN_PASSWORD?.trim() || demoPassword;
if (process.env.NODE_ENV === 'production' && adminPassword === demoPassword) {
  throw new Error('Set a unique SEED_ADMIN_PASSWORD before seeding production admin users.');
}
const adminDisplayName = process.env.SEED_ADMIN_DISPLAY_NAME?.trim() || 'Admin Reviewer';
const adminHandle = process.env.SEED_ADMIN_HANDLE?.trim() || 'admin';
const passwordHashCache = new Map<string, Promise<string>>();

function getPasswordHash(password: string) {
  const safePassword = password.trim();
  if (!safePassword || safePassword.length < 8) {
    throw new Error('Seed passwords must be at least 8 characters. Set SEED_DEMO_PASSWORD or SEED_ADMIN_PASSWORD.');
  }
  const cached = passwordHashCache.get(safePassword);
  if (cached) return cached;
  const hashPromise = bcrypt.hash(safePassword, 12);
  passwordHashCache.set(safePassword, hashPromise);
  return hashPromise;
}

type DemoUserInput = {
  email: string;
  displayName: string;
  handle: string;
  bio: string;
  role?: 'user' | 'admin';
  password?: string;
};

async function upsertDemoUser(input: DemoUserInput) {
  const passwordHash = await getPasswordHash(input.password ?? demoPassword);
  const role = input.role ?? 'user';

  const user = await prisma.user.upsert({
    where: { email: input.email },
    update: {
      passwordHash,
      role,
      emailVerifiedAt: new Date(),
      ageConfirmedAt: new Date(),
      declaredAgeBucket: '18_plus',
      termsAcceptedAt: new Date(),
      termsVersion: '2026-05-14',
      privacyVersion: '2026-05-14',
    },
    create: {
      email: input.email,
      passwordHash,
      role,
      emailVerifiedAt: new Date(),
      ageConfirmedAt: new Date(),
      declaredAgeBucket: '18_plus',
      termsAcceptedAt: new Date(),
      termsVersion: '2026-05-14',
      privacyVersion: '2026-05-14',
      profile: {
        create: {
          displayName: input.displayName,
          handle: input.handle,
          bio: input.bio,
          countryCode: 'FR',
          preferredCurrency: 'eur',
        },
      },
      settings: { create: {} },
      identities: {
        create: {
          provider: 'email',
          providerUserId: input.email,
          email: input.email,
        },
      },
    },
    include: { profile: true, settings: true },
  });

  await prisma.userIdentity.upsert({
    where: { provider_providerUserId: { provider: 'email', providerUserId: input.email } },
    update: { userId: user.id, email: input.email },
    create: { userId: user.id, provider: 'email', providerUserId: input.email, email: input.email },
  });

  await prisma.profile.upsert({
    where: { userId: user.id },
    update: {
      displayName: input.displayName,
      handle: input.handle,
      bio: input.bio,
      countryCode: 'FR',
      preferredCurrency: 'eur',
    },
    create: {
      userId: user.id,
      displayName: input.displayName,
      handle: input.handle,
      bio: input.bio,
      countryCode: 'FR',
      preferredCurrency: 'eur',
    },
  });

  await prisma.userSettings.upsert({
    where: { userId: user.id },
    update: {},
    create: { userId: user.id },
  });

  return user;
}

async function removeLegacyMoneyDemoData(userIds: string[]) {
  const legacyTickets = await prisma.supportTicket.findMany({
    where: {
      userId: { in: userIds },
      OR: [
        { category: 'credits_issue' },
        { subject: { contains: 'credit', mode: 'insensitive' } },
        { subject: { contains: 'Stripe', mode: 'insensitive' } },
      ],
    },
    select: { id: true },
  });
  const legacyTicketIds = legacyTickets.map((ticket) => ticket.id);

  if (legacyTicketIds.length) {
    await prisma.supportTicketMessage.deleteMany({ where: { ticketId: { in: legacyTicketIds } } });
    await prisma.supportTicket.deleteMany({ where: { id: { in: legacyTicketIds } } });
  }

  await prisma.creditLedgerEntry.deleteMany({ where: { userId: { in: userIds } } });
  await prisma.creditPurchase.deleteMany({ where: { userId: { in: userIds } } });
  await prisma.wallet.deleteMany({ where: { userId: { in: userIds } } });

  await prisma.trade.deleteMany({
    where: {
      ownerId: { in: userIds },
      OR: [
        { creditAmount: { gt: 0 } },
        { amountCents: { gt: 0 } },
        { title: { in: ['Need logo concept directions', 'Offer: profile bio rewrite'] } },
        { description: { contains: 'fake credit', mode: 'insensitive' } },
      ],
    },
  });
}

type SeedNeedData = Omit<Prisma.NeedUncheckedCreateInput, 'id' | 'ownerId' | 'title' | 'createdAt' | 'updatedAt'>;
type SeedOfferData = Omit<Prisma.OfferUncheckedCreateInput, 'id' | 'ownerId' | 'title' | 'createdAt' | 'updatedAt'>;
type SeedTradeData = Omit<Prisma.TradeUncheckedCreateInput, 'id' | 'ownerId' | 'title' | 'createdAt' | 'updatedAt' | 'creditAmount' | 'amountCents' | 'currency'>;
type SeedInventoryTemplateData = Omit<Prisma.InventoryTemplateUncheckedCreateInput, 'id' | 'createdAt' | 'updatedAt'>;

async function upsertNeed(ownerId: string, title: string, data: SeedNeedData) {
  const existing = await prisma.need.findFirst({ where: { ownerId, title } });
  if (existing) return prisma.need.update({ where: { id: existing.id }, data: data as Prisma.NeedUncheckedUpdateInput });
  return prisma.need.create({ data: { ownerId, title, ...data } as Prisma.NeedUncheckedCreateInput });
}

async function upsertOffer(ownerId: string, title: string, data: SeedOfferData) {
  const existing = await prisma.offer.findFirst({ where: { ownerId, title } });
  if (existing) return prisma.offer.update({ where: { id: existing.id }, data: data as Prisma.OfferUncheckedUpdateInput });
  return prisma.offer.create({ data: { ownerId, title, ...data } as Prisma.OfferUncheckedCreateInput });
}

async function upsertTrade(ownerId: string, title: string, data: SeedTradeData) {
  const safeData = {
    ...data,
    creditAmount: 0,
    amountCents: 0,
    currency: 'eur',
  };
  const existing = await prisma.trade.findFirst({ where: { ownerId, title } });
  if (existing) return prisma.trade.update({ where: { id: existing.id }, data: safeData as Prisma.TradeUncheckedUpdateInput });
  return prisma.trade.create({ data: { ownerId, title, ...safeData } as Prisma.TradeUncheckedCreateInput });
}

async function upsertInventoryTemplate(data: SeedInventoryTemplateData) {
  return prisma.inventoryTemplate.upsert({
    where: { key: data.key },
    update: data as Prisma.InventoryTemplateUncheckedUpdateInput,
    create: data as Prisma.InventoryTemplateUncheckedCreateInput,
  });
}

const starterInventoryTemplates: SeedInventoryTemplateData[] = [
  {
    key: 'starter-need-portfolio-photos-profile',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Portfolio photos for my profile',
    description: 'Use this when you need a few clean portraits or work-in-context photos for a freelance profile, portfolio, or social bio.',
    itemType: 'service',
    category: 'Photography',
    timing: 'This month',
    mode: 'hybrid',
    locationLabel: 'Paris / France or remote brief',
    tags: ['portfolio', 'portrait', 'freelance'],
    status: 'active',
    sortOrder: 10,
  },
  {
    key: 'starter-need-logo-visual-identity-feedback',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Feedback on my logo or identity',
    description: 'Start here when you want another creative to review your logo, colors, typography, or visual identity before you publish it.',
    itemType: 'service',
    category: 'Branding',
    timing: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['logo', 'branding', 'feedback'],
    status: 'active',
    sortOrder: 20,
  },
  {
    key: 'starter-need-landing-page-copy',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Help writing a landing page',
    description: 'Use this when your landing page needs clearer hero text, service sections, calls to action, or a friendlier launch message.',
    itemType: 'service',
    category: 'Copywriting',
    timing: 'Next few days',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['landing', 'copywriting', 'web'],
    status: 'active',
    sortOrder: 30,
  },
  {
    key: 'starter-need-website-review-before-launch',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Website review before launch',
    description: 'Use this when you want someone to check a simple website for clarity, mobile layout, broken links, and confusing steps before launch.',
    itemType: 'service',
    category: 'Web',
    timing: 'Today or tomorrow',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['website', 'review', 'launch'],
    status: 'active',
    sortOrder: 40,
  },
  {
    key: 'starter-need-french-correction-profile-offer',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'French correction for my profile',
    description: 'Start here when your French profile, service offer, or short presentation needs cleaner wording and simple correction.',
    itemType: 'service',
    category: 'Writing',
    timing: 'This week',
    mode: 'remote',
    locationLabel: 'France / remote',
    tags: ['french', 'profile', 'correction'],
    status: 'active',
    sortOrder: 50,
  },
  {
    key: 'starter-need-english-correction-portfolio',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'English correction for my portfolio',
    description: 'Use this when your English portfolio, profile, or offer text needs a practical review for clarity and natural wording.',
    itemType: 'service',
    category: 'Writing',
    timing: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['english', 'portfolio', 'writing'],
    status: 'active',
    sortOrder: 60,
  },
  {
    key: 'starter-need-social-post-ideas-service',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Social post ideas for my service',
    description: 'Use this when you need practical post ideas to explain a freelance service, project, workshop, or portfolio update.',
    itemType: 'service',
    category: 'Social Media',
    timing: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['social', 'content', 'ideas'],
    status: 'active',
    sortOrder: 70,
  },
  {
    key: 'starter-need-product-photos-small-project',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Product photos for a small project',
    description: 'Start here when you need simple product, craft, or portfolio photos for a launch page, profile, or social post.',
    itemType: 'service',
    category: 'Photography',
    timing: 'This month',
    mode: 'hybrid',
    locationLabel: 'Paris / France or remote brief',
    tags: ['product', 'photos', 'content'],
    status: 'active',
    sortOrder: 80,
  },
  {
    key: 'starter-need-short-intro-video-edit',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Edit a short intro video',
    description: 'Use this when you have a short intro, reel, or portfolio clip that needs cleaner cuts, captions, pacing, or export settings.',
    itemType: 'service',
    category: 'Video',
    timing: '48 hours',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['video', 'reel', 'editing'],
    status: 'active',
    sortOrder: 90,
  },
  {
    key: 'starter-need-pricing-page-feedback',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Feedback on my pricing page',
    description: 'Use this when you want feedback on the clarity, structure, and wording of a freelance pricing or packages page. No financial advice.',
    itemType: 'service',
    category: 'Business',
    timing: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['pricing', 'clarity', 'freelance'],
    status: 'active',
    sortOrder: 100,
  },
  {
    key: 'starter-need-linkedin-profile-improvement',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Improve my LinkedIn profile',
    description: 'Start here when your LinkedIn or freelance profile needs clearer positioning, headline ideas, and practical wording feedback.',
    itemType: 'service',
    category: 'Profile',
    timing: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['linkedin', 'profile', 'freelance'],
    status: 'active',
    sortOrder: 110,
  },
  {
    key: 'starter-need-booking-contact-form-test',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Test my booking/contact form',
    description: 'Use this when you want someone to try your booking, contact, or signup form and send notes about bugs or confusing steps.',
    itemType: 'service',
    category: 'Testing',
    timing: 'Today or tomorrow',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['testing', 'form', 'website'],
    status: 'active',
    sortOrder: 120,
  },
  {
    key: 'starter-need-brand-colors-fonts-review',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Brand color/font review',
    description: 'Use this when you want a simple review of your brand colors, fonts, spacing, and visual consistency before sharing publicly.',
    itemType: 'service',
    category: 'Branding',
    timing: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['brand', 'colors', 'fonts'],
    status: 'active',
    sortOrder: 130,
  },
  {
    key: 'starter-need-instagram-bio-copywriting',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Copywriting for my Instagram bio',
    description: 'Use this when your Instagram or creator bio needs to explain who you are, what you offer, and how people can contact you.',
    itemType: 'service',
    category: 'Copywriting',
    timing: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['instagram', 'bio', 'copy'],
    status: 'active',
    sortOrder: 140,
  },
  {
    key: 'starter-need-cv-portfolio-pdf-feedback',
    kind: 'need',
    sourceType: 'hellowhen',
    title: 'Feedback on my CV or portfolio PDF',
    description: 'Start here when you want practical feedback on the layout, wording, and readability of a CV, deck, or portfolio PDF.',
    itemType: 'service',
    category: 'Profile',
    timing: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['cv', 'portfolio', 'feedback'],
    status: 'active',
    sortOrder: 150,
  },
  {
    key: 'starter-offer-simple-portrait-photos',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can take simple portrait photos',
    description: 'Use this if you can take clean natural-light portraits for a freelance profile, portfolio page, or social bio.',
    itemType: 'service',
    category: 'Photography',
    availability: 'This month',
    mode: 'hybrid',
    locationLabel: 'Paris / France or remote brief',
    includes: ['Short shot list', 'Simple portraits', 'Basic edits'],
    tags: ['portrait', 'portfolio', 'photo'],
    status: 'active',
    sortOrder: 10,
  },
  {
    key: 'starter-offer-edit-product-portfolio-photos',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can edit product photos',
    description: 'Use this if you can clean up product, craft, or portfolio photos with basic cropping, color, and presentation edits.',
    itemType: 'service',
    category: 'Photography',
    availability: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Basic retouching', 'Export-ready files'],
    tags: ['photo', 'product', 'editing'],
    status: 'active',
    sortOrder: 20,
  },
  {
    key: 'starter-offer-review-landing-page',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can review your landing page',
    description: 'Use this if you can review a landing page and send friendly notes about clarity, structure, mobile layout, and calls to action.',
    itemType: 'service',
    category: 'Web',
    availability: 'Next few days',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Page notes', 'Priority fixes'],
    tags: ['landing', 'web', 'review'],
    status: 'active',
    sortOrder: 30,
  },
  {
    key: 'starter-offer-simple-social-media-post',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can design a social post',
    description: 'Use this if you can create a simple social media visual for a service, project announcement, or portfolio update.',
    itemType: 'service',
    category: 'Social Media',
    availability: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['One visual concept', 'Export file'],
    tags: ['social', 'design', 'content'],
    status: 'active',
    sortOrder: 40,
  },
  {
    key: 'starter-offer-logo-branding-feedback',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can give branding feedback',
    description: 'Use this if you can review a logo, color palette, font choice, or visual identity and send practical improvement notes.',
    itemType: 'service',
    category: 'Branding',
    availability: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Brand notes', 'Simple suggestions'],
    tags: ['logo', 'branding', 'feedback'],
    status: 'active',
    sortOrder: 50,
  },
  {
    key: 'starter-offer-clearer-website-copy',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can write clearer website copy',
    description: 'Use this if you can rewrite short website sections so a service, product, or portfolio is easier to understand.',
    itemType: 'service',
    category: 'Copywriting',
    availability: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Copy suggestions', 'One revision'],
    tags: ['copywriting', 'website', 'clarity'],
    status: 'active',
    sortOrder: 60,
  },
  {
    key: 'starter-offer-translate-french-english-text',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can translate French-English text',
    description: 'Use this if you can translate or lightly adapt short French and English profile, portfolio, or service text.',
    itemType: 'service',
    category: 'Translation',
    availability: 'This week',
    mode: 'remote',
    locationLabel: 'France / remote',
    includes: ['Short translation', 'Clarity pass'],
    tags: ['french', 'english', 'translation'],
    status: 'active',
    sortOrder: 70,
  },
  {
    key: 'starter-offer-linkedin-freelance-profile-review',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can review your LinkedIn profile',
    description: 'Use this if you can review a LinkedIn, creator, or freelance profile and suggest clearer headline and bio wording.',
    itemType: 'service',
    category: 'Profile',
    availability: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Profile notes', 'Headline ideas'],
    tags: ['linkedin', 'profile', 'freelance'],
    status: 'active',
    sortOrder: 80,
  },
  {
    key: 'starter-offer-notion-portfolio-structure',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can structure a Notion portfolio',
    description: 'Use this if you can help outline a simple Notion portfolio with sections for services, work samples, contact, and next steps.',
    itemType: 'service',
    category: 'No-code',
    availability: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Page structure', 'Section checklist'],
    tags: ['notion', 'portfolio', 'no-code'],
    status: 'active',
    sortOrder: 90,
  },
  {
    key: 'starter-offer-short-video-reel-edit',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can edit a short video or reel',
    description: 'Use this if you can edit a short intro video, reel, or portfolio clip with cleaner pacing, captions, and export settings.',
    itemType: 'service',
    category: 'Video',
    availability: '48 hours',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Short edit', 'Caption pass', 'Export'],
    tags: ['video', 'reel', 'editing'],
    status: 'active',
    sortOrder: 100,
  },
  {
    key: 'starter-offer-website-testing-feedback',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can test your website',
    description: 'Use this if you can click through a small website or form and send clear notes about bugs, confusing steps, and mobile issues.',
    itemType: 'service',
    category: 'Testing',
    availability: 'Today or tomorrow',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Test notes', 'Device/browser details'],
    tags: ['testing', 'website', 'feedback'],
    status: 'active',
    sortOrder: 110,
  },
  {
    key: 'starter-offer-organize-service-offer',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can organize your service offer',
    description: 'Use this if you can help turn a messy service idea into a clearer offer with audience, deliverables, and simple next steps.',
    itemType: 'service',
    category: 'Business',
    availability: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Offer outline', 'Clarity notes'],
    tags: ['service', 'positioning', 'freelance'],
    status: 'active',
    sortOrder: 120,
  },
  {
    key: 'starter-offer-basic-canva-visuals',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can create basic Canva visuals',
    description: 'Use this if you can create simple Canva visuals for a profile, post, event, or service announcement using user-provided content.',
    itemType: 'service',
    category: 'Design',
    availability: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Basic visual', 'Export file'],
    tags: ['canva', 'visuals', 'design'],
    status: 'active',
    sortOrder: 130,
  },
  {
    key: 'starter-offer-instagram-bio-improvement',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can improve your Instagram bio',
    description: 'Use this if you can rewrite a short Instagram or creator bio so it explains the person, offer, and contact path more clearly.',
    itemType: 'service',
    category: 'Copywriting',
    availability: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Bio rewrite', 'One revision'],
    tags: ['instagram', 'bio', 'copy'],
    status: 'active',
    sortOrder: 140,
  },
  {
    key: 'starter-offer-ux-feedback-app-website',
    kind: 'offer',
    sourceType: 'hellowhen',
    title: 'I can give UX feedback',
    description: 'Use this if you can review an app screen, website, or no-code prototype and send practical notes about clarity and flow.',
    itemType: 'service',
    category: 'UX',
    availability: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['UX notes', 'Priority fixes'],
    tags: ['ux', 'app', 'website'],
    status: 'active',
    sortOrder: 150,
  },
];

const frenchStarterInventoryTemplates: SeedInventoryTemplateData[] = [
  {
    key: 'starter-fr-need-portfolio-photos-profile',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Photos de portfolio pour mon profil',
    description: 'Utilisez ce modèle si vous avez besoin de portraits simples ou de photos en situation pour un profil freelance, portfolio ou bio sociale.',
    itemType: 'service',
    category: 'Photographie',
    timing: 'Ce mois-ci',
    mode: 'hybrid',
    locationLabel: 'Paris / France ou brief à distance',
    tags: ['portfolio', 'portrait', 'freelance'],
    status: 'active',
    sortOrder: 10,
  },
  {
    key: 'starter-fr-need-logo-visual-identity-feedback',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Avis sur mon logo ou identité',
    description: 'Utilisez ce modèle si vous voulez un avis créatif sur votre logo, vos couleurs, votre typographie ou votre identité visuelle avant publication.',
    itemType: 'service',
    category: 'Branding',
    timing: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    tags: ['logo', 'branding', 'avis'],
    status: 'active',
    sortOrder: 20,
  },
  {
    key: 'starter-fr-need-landing-page-copy',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Aide pour écrire une landing page',
    description: 'Utilisez ce modèle si votre landing page a besoin de textes plus clairs pour le hero, les services, les appels à l’action ou le lancement.',
    itemType: 'service',
    category: 'Rédaction',
    timing: 'Dans les prochains jours',
    mode: 'remote',
    locationLabel: 'À distance',
    tags: ['landing', 'rédaction', 'web'],
    status: 'active',
    sortOrder: 30,
  },
  {
    key: 'starter-fr-need-website-review-before-launch',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Revue de site avant lancement',
    description: 'Utilisez ce modèle si vous voulez vérifier la clarté, le rendu mobile, les liens et les étapes confuses d’un petit site avant lancement.',
    itemType: 'service',
    category: 'Web',
    timing: 'Aujourd’hui ou demain',
    mode: 'remote',
    locationLabel: 'À distance',
    tags: ['site', 'revue', 'lancement'],
    status: 'active',
    sortOrder: 40,
  },
  {
    key: 'starter-fr-need-french-correction-profile-offer',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Correction française pour mon profil',
    description: 'Utilisez ce modèle si votre profil, offre de service ou courte présentation en français a besoin d’une correction simple et claire.',
    itemType: 'service',
    category: 'Rédaction',
    timing: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'France / à distance',
    tags: ['français', 'profil', 'correction'],
    status: 'active',
    sortOrder: 50,
  },
  {
    key: 'starter-fr-need-english-correction-portfolio',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Correction anglaise pour mon portfolio',
    description: 'Utilisez ce modèle si votre portfolio, profil ou offre en anglais a besoin d’une revue pratique pour la clarté et le naturel du texte.',
    itemType: 'service',
    category: 'Rédaction',
    timing: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    tags: ['anglais', 'portfolio', 'rédaction'],
    status: 'active',
    sortOrder: 60,
  },
  {
    key: 'starter-fr-need-social-post-ideas-service',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Idées de posts pour mon service',
    description: 'Utilisez ce modèle si vous avez besoin d’idées de posts simples pour expliquer un service freelance, un projet, un atelier ou une mise à jour de portfolio.',
    itemType: 'service',
    category: 'Réseaux sociaux',
    timing: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    tags: ['social', 'contenu', 'idées'],
    status: 'active',
    sortOrder: 70,
  },
  {
    key: 'starter-fr-need-product-photos-small-project',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Photos produit pour un petit projet',
    description: 'Utilisez ce modèle si vous avez besoin de photos simples pour un produit, une création, une page de lancement, un profil ou un post social.',
    itemType: 'service',
    category: 'Photographie',
    timing: 'Ce mois-ci',
    mode: 'hybrid',
    locationLabel: 'Paris / France ou brief à distance',
    tags: ['produit', 'photos', 'contenu'],
    status: 'active',
    sortOrder: 80,
  },
  {
    key: 'starter-fr-need-short-intro-video-edit',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Montage d’une courte vidéo intro',
    description: 'Utilisez ce modèle si une intro, un reel ou une vidéo de portfolio a besoin de coupes plus propres, sous-titres, rythme ou réglages d’export.',
    itemType: 'service',
    category: 'Vidéo',
    timing: '48 heures',
    mode: 'remote',
    locationLabel: 'À distance',
    tags: ['vidéo', 'reel', 'montage'],
    status: 'active',
    sortOrder: 90,
  },
  {
    key: 'starter-fr-need-pricing-page-feedback',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Avis sur ma page de tarifs',
    description: 'Utilisez ce modèle si vous voulez un avis sur la clarté, la structure et le texte d’une page de tarifs ou packages freelance. Aucun conseil financier.',
    itemType: 'service',
    category: 'Business',
    timing: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    tags: ['tarifs', 'clarté', 'freelance'],
    status: 'active',
    sortOrder: 100,
  },
  {
    key: 'starter-fr-need-linkedin-profile-improvement',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Améliorer mon profil LinkedIn',
    description: 'Utilisez ce modèle si votre profil LinkedIn ou freelance a besoin d’un positionnement plus clair, d’idées de titre et de retours sur le texte.',
    itemType: 'service',
    category: 'Profil',
    timing: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    tags: ['linkedin', 'profil', 'freelance'],
    status: 'active',
    sortOrder: 110,
  },
  {
    key: 'starter-fr-need-booking-contact-form-test',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Tester mon formulaire de contact',
    description: 'Utilisez ce modèle si vous voulez qu’une personne teste un formulaire de réservation, contact ou inscription et signale bugs ou étapes confuses.',
    itemType: 'service',
    category: 'Test',
    timing: 'Aujourd’hui ou demain',
    mode: 'remote',
    locationLabel: 'À distance',
    tags: ['test', 'formulaire', 'site'],
    status: 'active',
    sortOrder: 120,
  },
  {
    key: 'starter-fr-need-brand-colors-fonts-review',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Revue couleurs et polices',
    description: 'Utilisez ce modèle si vous voulez une revue simple de vos couleurs, polices, espacements et cohérence visuelle avant publication.',
    itemType: 'service',
    category: 'Branding',
    timing: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    tags: ['marque', 'couleurs', 'polices'],
    status: 'active',
    sortOrder: 130,
  },
  {
    key: 'starter-fr-need-instagram-bio-copywriting',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Rédaction pour ma bio Instagram',
    description: 'Utilisez ce modèle si votre bio Instagram ou créateur doit expliquer qui vous êtes, ce que vous proposez et comment vous contacter.',
    itemType: 'service',
    category: 'Rédaction',
    timing: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    tags: ['instagram', 'bio', 'rédaction'],
    status: 'active',
    sortOrder: 140,
  },
  {
    key: 'starter-fr-need-cv-portfolio-pdf-feedback',
    kind: 'need',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Avis sur mon CV ou portfolio PDF',
    description: 'Utilisez ce modèle si vous voulez un retour pratique sur la mise en page, le texte et la lisibilité d’un CV, deck ou portfolio PDF.',
    itemType: 'service',
    category: 'Profil',
    timing: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    tags: ['cv', 'portfolio', 'avis'],
    status: 'active',
    sortOrder: 150,
  },
  {
    key: 'starter-fr-offer-simple-portrait-photos',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux prendre des portraits simples',
    description: 'Utilisez ce modèle si vous pouvez prendre des portraits naturels et propres pour un profil freelance, une page portfolio ou une bio sociale.',
    itemType: 'service',
    category: 'Photographie',
    availability: 'Ce mois-ci',
    mode: 'hybrid',
    locationLabel: 'Paris / France ou brief à distance',
    includes: ['Mini shot list', 'Portraits simples', 'Retouches de base'],
    tags: ['portrait', 'portfolio', 'photo'],
    status: 'active',
    sortOrder: 10,
  },
  {
    key: 'starter-fr-offer-edit-product-portfolio-photos',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux retoucher des photos produit',
    description: 'Utilisez ce modèle si vous pouvez nettoyer des photos produit, création ou portfolio avec recadrage, couleur et présentation simple.',
    itemType: 'service',
    category: 'Photographie',
    availability: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Retouche de base', 'Fichiers prêts à publier'],
    tags: ['photo', 'produit', 'retouche'],
    status: 'active',
    sortOrder: 20,
  },
  {
    key: 'starter-fr-offer-review-landing-page',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux relire votre landing page',
    description: 'Utilisez ce modèle si vous pouvez relire une landing page et envoyer des notes sur la clarté, la structure, le mobile et les appels à l’action.',
    itemType: 'service',
    category: 'Web',
    availability: 'Dans les prochains jours',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Notes de page', 'Corrections prioritaires'],
    tags: ['landing', 'web', 'revue'],
    status: 'active',
    sortOrder: 30,
  },
  {
    key: 'starter-fr-offer-simple-social-media-post',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux créer un post social',
    description: 'Utilisez ce modèle si vous pouvez créer un visuel simple pour présenter un service, annoncer un projet ou mettre à jour un portfolio.',
    itemType: 'service',
    category: 'Réseaux sociaux',
    availability: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Un concept visuel', 'Fichier exporté'],
    tags: ['social', 'design', 'contenu'],
    status: 'active',
    sortOrder: 40,
  },
  {
    key: 'starter-fr-offer-logo-branding-feedback',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux donner un avis branding',
    description: 'Utilisez ce modèle si vous pouvez relire un logo, une palette, un choix de police ou une identité visuelle et envoyer des notes pratiques.',
    itemType: 'service',
    category: 'Branding',
    availability: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Notes branding', 'Suggestions simples'],
    tags: ['logo', 'branding', 'avis'],
    status: 'active',
    sortOrder: 50,
  },
  {
    key: 'starter-fr-offer-clearer-website-copy',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux clarifier du texte web',
    description: 'Utilisez ce modèle si vous pouvez réécrire de courts textes web pour rendre un service, produit ou portfolio plus facile à comprendre.',
    itemType: 'service',
    category: 'Rédaction',
    availability: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Suggestions de texte', 'Une révision'],
    tags: ['rédaction', 'site', 'clarté'],
    status: 'active',
    sortOrder: 60,
  },
  {
    key: 'starter-fr-offer-translate-french-english-text',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux traduire français-anglais',
    description: 'Utilisez ce modèle si vous pouvez traduire ou adapter légèrement un court texte de profil, portfolio ou offre en français et anglais.',
    itemType: 'service',
    category: 'Traduction',
    availability: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'France / à distance',
    includes: ['Traduction courte', 'Passage clarté'],
    tags: ['français', 'anglais', 'traduction'],
    status: 'active',
    sortOrder: 70,
  },
  {
    key: 'starter-fr-offer-linkedin-freelance-profile-review',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux relire votre profil LinkedIn',
    description: 'Utilisez ce modèle si vous pouvez relire un profil LinkedIn, créateur ou freelance et suggérer un titre et une bio plus clairs.',
    itemType: 'service',
    category: 'Profil',
    availability: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Notes de profil', 'Idées de titre'],
    tags: ['linkedin', 'profil', 'freelance'],
    status: 'active',
    sortOrder: 80,
  },
  {
    key: 'starter-fr-offer-notion-portfolio-structure',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux structurer un portfolio Notion',
    description: 'Utilisez ce modèle si vous pouvez aider à structurer un portfolio Notion avec services, exemples, contact et prochaines étapes.',
    itemType: 'service',
    category: 'No-code',
    availability: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Structure de page', 'Checklist de sections'],
    tags: ['notion', 'portfolio', 'no-code'],
    status: 'active',
    sortOrder: 90,
  },
  {
    key: 'starter-fr-offer-short-video-reel-edit',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux monter une courte vidéo',
    description: 'Utilisez ce modèle si vous pouvez monter une intro, un reel ou une vidéo portfolio avec meilleur rythme, sous-titres et export.',
    itemType: 'service',
    category: 'Vidéo',
    availability: '48 heures',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Montage court', 'Passage sous-titres', 'Export'],
    tags: ['vidéo', 'reel', 'montage'],
    status: 'active',
    sortOrder: 100,
  },
  {
    key: 'starter-fr-offer-website-testing-feedback',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux tester votre site',
    description: 'Utilisez ce modèle si vous pouvez parcourir un petit site ou formulaire et envoyer des notes sur les bugs, étapes confuses et problèmes mobiles.',
    itemType: 'service',
    category: 'Test',
    availability: 'Aujourd’hui ou demain',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Notes de test', 'Détails appareil/navigateur'],
    tags: ['test', 'site', 'avis'],
    status: 'active',
    sortOrder: 110,
  },
  {
    key: 'starter-fr-offer-organize-service-offer',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux organiser votre offre',
    description: 'Utilisez ce modèle si vous pouvez transformer une idée de service floue en une offre plus claire avec cible, livrables et prochaines étapes.',
    itemType: 'service',
    category: 'Business',
    availability: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Structure d’offre', 'Notes de clarté'],
    tags: ['service', 'positionnement', 'freelance'],
    status: 'active',
    sortOrder: 120,
  },
  {
    key: 'starter-fr-offer-basic-canva-visuals',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux créer des visuels Canva',
    description: 'Utilisez ce modèle si vous pouvez créer des visuels Canva simples pour un profil, post, événement ou service avec le contenu fourni.',
    itemType: 'service',
    category: 'Design',
    availability: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Visuel simple', 'Fichier exporté'],
    tags: ['canva', 'visuels', 'design'],
    status: 'active',
    sortOrder: 130,
  },
  {
    key: 'starter-fr-offer-instagram-bio-improvement',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux améliorer votre bio Instagram',
    description: 'Utilisez ce modèle si vous pouvez réécrire une courte bio Instagram ou créateur pour mieux expliquer la personne, l’offre et le contact.',
    itemType: 'service',
    category: 'Rédaction',
    availability: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Bio réécrite', 'Une révision'],
    tags: ['instagram', 'bio', 'rédaction'],
    status: 'active',
    sortOrder: 140,
  },
  {
    key: 'starter-fr-offer-ux-feedback-app-website',
    kind: 'offer',
    sourceType: 'hellowhen',
    languageCode: 'fr',
    countryCode: null,
    title: 'Je peux donner un avis UX',
    description: 'Utilisez ce modèle si vous pouvez relire un écran d’app, site ou prototype no-code et envoyer des notes pratiques sur la clarté et le parcours.',
    itemType: 'service',
    category: 'UX',
    availability: 'Cette semaine',
    mode: 'remote',
    locationLabel: 'À distance',
    includes: ['Notes UX', 'Corrections prioritaires'],
    tags: ['ux', 'app', 'site'],
    status: 'active',
    sortOrder: 150,
  },
];

async function seedStarterInventoryTemplates() {
  const activeStarterTemplates = [...starterInventoryTemplates, ...frenchStarterInventoryTemplates];
  const activeStarterKeys = activeStarterTemplates.map((template) => template.key);

  for (const template of activeStarterTemplates) {
    await upsertInventoryTemplate({ languageCode: 'en', countryCode: null, ...template });
  }

  await prisma.inventoryTemplate.updateMany({
    where: {
      sourceType: 'hellowhen',
      key: { startsWith: 'starter-', notIn: activeStarterKeys },
      status: 'active',
    },
    data: { status: 'archived' },
  });
}

async function main() {
  const demo = await upsertDemoUser({
    email: 'demo@hellowhen.app',
    displayName: 'Demo Owner',
    handle: 'demo',
    bio: 'Demo owner account for testing Need, Offer, Trade, and proposal flows.',
  });

  const helper = await upsertDemoUser({
    email: 'helper@hellowhen.app',
    displayName: 'Helper User',
    handle: 'helper',
    bio: 'Demo helper account for sending proposals and completing service or goods exchanges.',
  });

  const admin = await upsertDemoUser({
    email: adminEmail,
    displayName: adminDisplayName,
    handle: adminHandle,
    bio: 'Demo admin account for reviewing support tickets and safety reports.',
    role: 'admin',
    password: adminPassword,
  });

  await removeLegacyMoneyDemoData([demo.id, helper.id, admin.id]);
  await seedStarterInventoryTemplates();

  const demoNeed = await upsertNeed(demo.id, 'Landing page hero review', {
    description: 'I need feedback on headline, CTA, and first fold for a small product launch page.',
    itemType: 'service',
    category: 'Design',
    timing: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['design', 'launch'],
    status: 'active',
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7),
  });

  const demoOffer = await upsertOffer(demo.id, 'Product photo notes', {
    description: 'I can review product photos and suggest a cleaner shot list for a launch page or social post.',
    itemType: 'service',
    category: 'Photography',
    availability: 'Weekend',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Shot-list feedback', 'Simple composition notes'],
    tags: ['photos', 'launch'],
    status: 'active',
  });

  const helperNeed = await upsertNeed(helper.id, 'Short launch video edit', {
    description: 'I need help polishing a 45-second launch video and exporting it for mobile and social.',
    itemType: 'service',
    category: 'Video',
    timing: '24–48 hours',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['video', 'launch'],
    status: 'active',
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5),
  });

  const helperOffer = await upsertOffer(helper.id, 'Brand naming feedback', {
    description: 'I can review names and give concise positioning feedback for early product ideas.',
    itemType: 'service',
    category: 'Branding',
    availability: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['Name shortlist review', 'Positioning notes'],
    tags: ['branding', 'naming'],
    status: 'active',
  });

  const goodsNeed = await upsertNeed(helper.id, 'Need simple product styling props', {
    description: 'I need a few clean styling props for a small product photo session.',
    itemType: 'goods',
    category: 'Goods',
    timing: 'Next week',
    mode: 'local',
    locationLabel: 'Local pickup',
    tags: ['props', 'photos'],
    status: 'active',
  });

  const goodsOffer = await upsertOffer(helper.id, 'Offer sample product pack', {
    description: 'I can provide a small sample pack for content testing or styling reference.',
    itemType: 'goods',
    category: 'Goods',
    availability: 'This week',
    mode: 'local',
    locationLabel: 'Local pickup',
    includes: ['Sample pack', 'Pickup details after acceptance'],
    tags: ['samples', 'goods'],
    status: 'active',
  });

  const openTrade = await upsertTrade(demo.id, 'Landing page hero review ↔ Product photo notes', {
    needId: demoNeed.id,
    offerId: demoOffer.id,
    description: 'I need a clearer landing page hero and can offer product photo notes in return.',
    status: 'active',
    isPublic: true,
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7),
  });

  const helperTrade = await upsertTrade(helper.id, 'Short launch video edit ↔ Brand naming feedback', {
    needId: helperNeed.id,
    offerId: helperOffer.id,
    description: 'I need help editing a short launch video and can offer brand naming feedback in return.',
    status: 'active',
    isPublic: true,
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5),
  });

  await upsertTrade(helper.id, 'Product styling props ↔ Sample product pack', {
    needId: goodsNeed.id,
    offerId: goodsOffer.id,
    description: 'I need simple styling props and can offer a sample product pack for content testing.',
    status: 'active',
    isPublic: true,
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10),
  });


  const stressTradeFixtures = [
    {
      ownerId: demo.id,
      needTitle: 'Need editor for short product video',
      needDescription: 'I need a clean edit for a vertical product video with captions, light sound cleanup, and a punchy hook.',
      needType: 'service' as const,
      needCategory: 'Video',
      needTiming: 'This weekend',
      needMode: 'remote' as const,
      needLocation: 'Remote',
      needTags: ['video', 'editing', 'remote'],
      offerTitle: 'UI polish for web app',
      offerDescription: 'I can review a web app screen and send a clear UI polish checklist with spacing, hierarchy, and copy notes.',
      offerType: 'service' as const,
      offerCategory: 'Design',
      offerAvailability: 'Any time',
      offerMode: 'remote' as const,
      offerLocation: 'Remote',
      offerIncludes: ['UI notes', 'Spacing review', 'One screen'],
      offerTags: ['design', 'ui', 'web'],
    },
    {
      ownerId: demo.id,
      needTitle: 'Need homepage copy cleanup',
      needDescription: 'I need someone to tighten homepage copy and make the first section easier to understand.',
      needType: 'service' as const,
      needCategory: 'Copywriting',
      needTiming: 'Next 3 days',
      needMode: 'remote' as const,
      needLocation: 'Remote',
      needTags: ['copy', 'homepage'],
      offerTitle: 'Figma component tidy-up',
      offerDescription: 'I can organize a small Figma file, rename layers, and clean up a starter component set.',
      offerType: 'service' as const,
      offerCategory: 'Design',
      offerAvailability: 'Evenings',
      offerMode: 'remote' as const,
      offerLocation: 'Remote',
      offerIncludes: ['Layer cleanup', 'Component naming'],
      offerTags: ['figma', 'design'],
    },
    {
      ownerId: demo.id,
      needTitle: 'Need marketplace onboarding review',
      needDescription: 'I need feedback on a short onboarding flow for first-time marketplace users.',
      needType: 'service' as const,
      needCategory: 'Product',
      needTiming: 'This week',
      needMode: 'remote' as const,
      needLocation: 'Remote',
      needTags: ['product', 'ux'],
      offerTitle: 'Landing page hero mockup',
      offerDescription: 'I can create one quick landing page hero mockup with headline, CTA, and a simple layout direction.',
      offerType: 'service' as const,
      offerCategory: 'Design',
      offerAvailability: 'This week',
      offerMode: 'remote' as const,
      offerLocation: 'Remote',
      offerIncludes: ['Hero mockup', 'CTA direction'],
      offerTags: ['landing', 'mockup'],
    },
    {
      ownerId: demo.id,
      needTitle: 'Need product photo retouching',
      needDescription: 'I need five product photos cleaned up with background and light color correction.',
      needType: 'service' as const,
      needCategory: 'Photography',
      needTiming: '48 hours',
      needMode: 'remote' as const,
      needLocation: 'Remote',
      needTags: ['photo', 'retouch'],
      offerTitle: 'Short app store copy',
      offerDescription: 'I can write a short app store description and three concise feature bullets.',
      offerType: 'service' as const,
      offerCategory: 'Copywriting',
      offerAvailability: 'Tomorrow',
      offerMode: 'remote' as const,
      offerLocation: 'Remote',
      offerIncludes: ['App description', 'Feature bullets'],
      offerTags: ['copy', 'app'],
    },
    {
      ownerId: demo.id,
      needTitle: 'Need simple icon concepts',
      needDescription: 'I need three simple monochrome icon concept directions for a mobile tab bar.',
      needType: 'service' as const,
      needCategory: 'Icon design',
      needTiming: 'Flexible',
      needMode: 'remote' as const,
      needLocation: 'Remote',
      needTags: ['icons', 'mobile'],
      offerTitle: 'Bug reproduction notes',
      offerDescription: 'I can test a web page on mobile and desktop and write clean reproduction notes for visible bugs.',
      offerType: 'service' as const,
      offerCategory: 'QA',
      offerAvailability: 'Weekend',
      offerMode: 'remote' as const,
      offerLocation: 'Remote',
      offerIncludes: ['Bug notes', 'Screenshots'],
      offerTags: ['qa', 'testing'],
    },
    {
      ownerId: demo.id,
      needTitle: 'Need local pickup help',
      needDescription: 'I need someone nearby to pick up a small package and bring it to a local studio.',
      needType: 'other' as const,
      needCategory: 'Errand',
      needTiming: 'Friday',
      needMode: 'local' as const,
      needLocation: 'Paris area',
      needTags: ['local', 'pickup'],
      offerTitle: 'Product listing cleanup',
      offerDescription: 'I can clean up product listing text and make the title, bullets, and description easier to scan.',
      offerType: 'service' as const,
      offerCategory: 'Ecommerce',
      offerAvailability: 'This week',
      offerMode: 'remote' as const,
      offerLocation: 'Remote',
      offerIncludes: ['Title cleanup', 'Bullet rewrite'],
      offerTags: ['ecommerce', 'copy'],
    },
    {
      ownerId: demo.id,
      needTitle: 'Need beta tester for mobile web',
      needDescription: 'I need someone to test mobile web layout with multiple trades, long text, and form scrolling.',
      needType: 'service' as const,
      needCategory: 'Testing',
      needTiming: 'Today',
      needMode: 'remote' as const,
      needLocation: 'Remote',
      needTags: ['testing', 'mobile'],
      offerTitle: 'Profile bio rewrite',
      offerDescription: 'I can rewrite a short creator or freelancer profile bio with a clearer offer and tone.',
      offerType: 'service' as const,
      offerCategory: 'Writing',
      offerAvailability: 'Today',
      offerMode: 'remote' as const,
      offerLocation: 'Remote',
      offerIncludes: ['Bio rewrite', 'One revision'],
      offerTags: ['bio', 'writing'],
    },
    {
      ownerId: helper.id,
      needTitle: 'Need quick SEO title audit',
      needDescription: 'I need help checking page titles and descriptions for a small marketing site.',
      needType: 'service' as const,
      needCategory: 'Marketing',
      needTiming: 'Next week',
      needMode: 'remote' as const,
      needLocation: 'Remote',
      needTags: ['seo', 'marketing'],
      offerTitle: 'Video thumbnail feedback',
      offerDescription: 'I can review three video thumbnails and suggest better hierarchy and contrast.',
      offerType: 'service' as const,
      offerCategory: 'Video',
      offerAvailability: 'Evenings',
      offerMode: 'remote' as const,
      offerLocation: 'Remote',
      offerIncludes: ['Thumbnail review', 'Contrast notes'],
      offerTags: ['video', 'thumbnail'],
    },
    {
      ownerId: helper.id,
      needTitle: 'Need product sample styling',
      needDescription: 'I need styling ideas for a small product sample pack before taking photos.',
      needType: 'goods' as const,
      needCategory: 'Goods',
      needTiming: 'This month',
      needMode: 'hybrid' as const,
      needLocation: 'Local or remote',
      needTags: ['goods', 'styling'],
      offerTitle: 'Remote usability notes',
      offerDescription: 'I can give usability notes for one mobile flow with screenshots and priority fixes.',
      offerType: 'service' as const,
      offerCategory: 'UX',
      offerAvailability: 'This week',
      offerMode: 'remote' as const,
      offerLocation: 'Remote',
      offerIncludes: ['UX notes', 'Priority fixes'],
      offerTags: ['ux', 'mobile'],
    },
    {
      ownerId: helper.id,
      needTitle: 'Need intro email polish',
      needDescription: 'I need a concise intro email polished so it feels friendly and clear.',
      needType: 'service' as const,
      needCategory: 'Email',
      needTiming: 'Tomorrow',
      needMode: 'remote' as const,
      needLocation: 'Remote',
      needTags: ['email', 'copy'],
      offerTitle: 'Small logo direction notes',
      offerDescription: 'I can give notes on simple logo directions and help choose the cleanest option.',
      offerType: 'service' as const,
      offerCategory: 'Branding',
      offerAvailability: 'Tomorrow',
      offerMode: 'remote' as const,
      offerLocation: 'Remote',
      offerIncludes: ['Logo notes', 'Direction choice'],
      offerTags: ['logo', 'brand'],
    },
  ];

  for (const [index, fixture] of stressTradeFixtures.entries()) {
    const need = await upsertNeed(fixture.ownerId, fixture.needTitle, {
      description: fixture.needDescription,
      itemType: fixture.needType,
      category: fixture.needCategory,
      timing: fixture.needTiming,
      mode: fixture.needMode,
      locationLabel: fixture.needLocation,
      tags: fixture.needTags,
      status: 'active',
      expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * (6 + index)),
    });
    const offer = await upsertOffer(fixture.ownerId, fixture.offerTitle, {
      description: fixture.offerDescription,
      itemType: fixture.offerType,
      category: fixture.offerCategory,
      availability: fixture.offerAvailability,
      mode: fixture.offerMode,
      locationLabel: fixture.offerLocation,
      includes: fixture.offerIncludes,
      tags: fixture.offerTags,
      status: 'active',
    });
    await upsertTrade(fixture.ownerId, `${fixture.needTitle} ↔ ${fixture.offerTitle}`, {
      needId: need.id,
      offerId: offer.id,
      description: `${fixture.needDescription} In exchange, ${fixture.offerDescription.toLowerCase()}`,
      status: 'active',
      isPublic: true,
      expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * (6 + index)),
    });
  }

  const existingProposal = await prisma.tradeProposal.findUnique({
    where: { tradeId_applicantId: { tradeId: openTrade.id, applicantId: helper.id } },
  });

  if (!existingProposal) {
    const proposal = await prisma.tradeProposal.create({
      data: {
        tradeId: openTrade.id,
        applicantId: helper.id,
        message: 'I can review the hero section and send a concise set of layout and copy notes tomorrow.',
      },
    });
    await prisma.proposalMessage.create({ data: { proposalId: proposal.id, senderId: helper.id, body: proposal.message } });
    await prisma.proposalMessage.create({ data: { proposalId: proposal.id, senderId: demo.id, body: 'Great — please focus on clarity and the first call to action.' } });
  }

  const existingSupportTicket = await prisma.supportTicket.findFirst({
    where: { userId: demo.id, subject: 'Need help with a trade proposal' },
  });

  if (!existingSupportTicket) {
    const ticket = await prisma.supportTicket.create({
      data: {
        userId: demo.id,
        category: 'trade_issue',
        priority: 'normal',
        subject: 'Need help with a trade proposal',
        message: 'I want to understand whether I should accept a proposal before the other person has confirmed the timeline.',
        relatedTradeId: openTrade.id,
      },
    });
    await prisma.supportTicketMessage.create({ data: { ticketId: ticket.id, senderId: demo.id, senderRole: 'user', body: ticket.message } });
    await prisma.supportTicketMessage.create({ data: { ticketId: ticket.id, senderId: admin.id, senderRole: 'admin', body: 'Ask for a clear delivery timeline in the proposal thread before accepting.' } });
    await prisma.supportTicket.update({ where: { id: ticket.id }, data: { status: 'waiting_for_user', assignedAdminId: admin.id } });
  }

  console.log('Seeded beta-safe demo accounts, starter Need/Offer templates, expanded inventory, stress-test trades, proposal flow, and support ticket flow.');
  console.log(`Owner:  demo@hellowhen.app / ${demoPassword}`);
  console.log(`Helper: helper@hellowhen.app / ${demoPassword}`);
  console.log(`Admin:  ${adminEmail} / [hidden]`);
  if (adminPassword === 'password123') {
    console.log('Admin setup warning: SEED_ADMIN_PASSWORD is using the default local demo password. Change it outside local development.');
  }
  console.log('Admin setup note: if ADMIN_REQUIRE_TWO_FACTOR=true, enable authenticator 2FA on the admin account before using /admin tools, or set ADMIN_REQUIRE_TWO_FACTOR=false only for local smoke tests.');
  console.log(`Sample trades: ${openTrade.title}; ${helperTrade.title}`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
