import { z } from 'zod';
export declare const businessProfileTypeSchema: z.ZodEnum<{
    business: "business";
    agency: "agency";
    brand: "brand";
    enterprise: "enterprise";
}>;
export declare const businessProfileStatusSchema: z.ZodEnum<{
    draft: "draft";
    active: "active";
    pending_review: "pending_review";
    verified: "verified";
    restricted: "restricted";
    disabled: "disabled";
    rejected: "rejected";
}>;
export declare const businessProfileMemberRoleSchema: z.ZodEnum<{
    owner: "owner";
    admin: "admin";
    finance: "finance";
    member: "member";
}>;
export declare const businessProfileInvitationStatusSchema: z.ZodEnum<{
    pending: "pending";
    accepted: "accepted";
    revoked: "revoked";
    expired: "expired";
}>;
export declare const businessSponsoredPlacementSurfaceSchema: z.ZodEnum<{
    trades_feed: "trades_feed";
    starter_library: "starter_library";
    needs_list: "needs_list";
    offers_list: "offers_list";
    business_profile: "business_profile";
}>;
export declare const businessSponsoredPlacementTargetTypeSchema: z.ZodEnum<{
    need: "need";
    offer: "offer";
    inventory_template: "inventory_template";
}>;
export declare const businessSponsoredPlacementStatusSchema: z.ZodEnum<{
    draft: "draft";
    pending_review: "pending_review";
    approved: "approved";
    rejected: "rejected";
    paused: "paused";
    archived: "archived";
}>;
export declare const businessCampaignOpportunityTypeSchema: z.ZodEnum<{
    collaboration: "collaboration";
    creator_request: "creator_request";
    service_request: "service_request";
    community: "community";
    research: "research";
    other: "other";
}>;
export declare const businessCampaignStatusSchema: z.ZodEnum<{
    draft: "draft";
    pending_review: "pending_review";
    approved: "approved";
    rejected: "rejected";
    paused: "paused";
    archived: "archived";
    completed: "completed";
}>;
export declare const businessCampaignItemTargetTypeSchema: z.ZodEnum<{
    need: "need";
    offer: "offer";
    inventory_template: "inventory_template";
}>;
export declare const businessCampaignApplicationStatusSchema: z.ZodEnum<{
    pending: "pending";
    reviewed: "reviewed";
    accepted: "accepted";
    declined: "declined";
    withdrawn: "withdrawn";
    archived: "archived";
}>;
export declare const businessBudgetStatusSchema: z.ZodEnum<{
    draft: "draft";
    pending_provider_review: "pending_provider_review";
    pending_admin_review: "pending_admin_review";
    sandbox_ready: "sandbox_ready";
    rejected: "rejected";
    paused: "paused";
    archived: "archived";
}>;
export declare const businessBudgetLedgerEntryTypeSchema: z.ZodEnum<{
    requested: "requested";
    reserved_preview: "reserved_preview";
    spend_preview: "spend_preview";
    refund_preview: "refund_preview";
    platform_fee_preview: "platform_fee_preview";
    adjustment: "adjustment";
}>;
export declare const businessBudgetProviderSchema: z.ZodEnum<{
    none: "none";
    stripe: "stripe";
    airwallex: "airwallex";
}>;
export declare const createBusinessProfileRequestSchema: z.ZodObject<any>;
export declare const updateBusinessProfileRequestSchema: z.ZodObject<any>;
export declare const requestBusinessReviewRequestSchema: z.ZodObject<any>;
export declare const businessProviderOnboardingLinkRequestSchema: z.ZodObject<any>;
export declare const businessInviteMemberRequestSchema: z.ZodObject<any>;
export declare const businessUpdateMemberRequestSchema: z.ZodObject<any>;
export declare const businessRemoveMemberRequestSchema: z.ZodObject<any>;
export declare const businessInvitationActionRequestSchema: z.ZodObject<any>;
export declare const businessAcceptInvitationRequestSchema: z.ZodObject<any>;
export declare const businessCreateInventoryTemplateRequestSchema: z.ZodObject<any>;
export declare const businessUpdateInventoryTemplateRequestSchema: z.ZodType<any>;
export declare const businessListInventoryTemplatesQuerySchema: z.ZodObject<any>;
export declare const businessInventoryTemplateReviewRequestSchema: z.ZodObject<any>;
export declare const businessInventoryTemplateArchiveRequestSchema: z.ZodObject<any>;
export declare const businessCreateNeedRequestSchema: z.ZodObject<any>;
export declare const businessCreateOfferRequestSchema: z.ZodObject<any>;
export declare const businessUpdateNeedRequestSchema: z.ZodObject<any>;
export declare const businessUpdateOfferRequestSchema: z.ZodObject<any>;
export declare const businessListOwnedInventoryQuerySchema: z.ZodObject<any>;
export declare const businessOwnedInventoryReviewRequestSchema: z.ZodObject<any>;
export declare const businessOwnedInventoryArchiveRequestSchema: z.ZodObject<any>;
export declare const businessSponsoredPlacementListQuerySchema: z.ZodObject<any>;
export declare const businessCreateSponsoredPlacementRequestSchema: z.ZodType<any>;
export declare const businessUpdateSponsoredPlacementRequestSchema: z.ZodType<any>;
export declare const businessSponsoredPlacementReviewRequestSchema: z.ZodObject<any>;
export declare const businessSponsoredPlacementArchiveRequestSchema: z.ZodObject<any>;
export declare const businessCampaignListQuerySchema: z.ZodObject<any>;
export declare const businessCreateCampaignRequestSchema: z.ZodType<any>;
export declare const businessUpdateCampaignRequestSchema: z.ZodType<any>;
export declare const businessCampaignReviewRequestSchema: z.ZodObject<any>;
export declare const businessCampaignArchiveRequestSchema: z.ZodObject<any>;
export declare const businessCreateCampaignItemRequestSchema: z.ZodObject<any>;
export declare const businessUpdateCampaignItemRequestSchema: z.ZodType<any>;
export declare const businessCampaignItemActionRequestSchema: z.ZodObject<any>;
export declare const businessBudgetListQuerySchema: z.ZodObject<any>;
export declare const businessCreateBudgetRequestSchema: z.ZodType<any>;
export declare const businessUpdateBudgetRequestSchema: z.ZodType<any>;
export declare const businessBudgetReviewRequestSchema: z.ZodObject<any>;
export declare const businessBudgetArchiveRequestSchema: z.ZodObject<any>;
export declare const adminBusinessCampaignListQuerySchema: z.ZodObject<any>;
export declare const adminBusinessCampaignActionRequestSchema: z.ZodObject<any>;
export declare const adminBusinessBudgetListQuerySchema: z.ZodObject<any>;
export declare const adminBusinessBudgetActionRequestSchema: z.ZodObject<any>;
export declare const adminBusinessSponsoredPlacementListQuerySchema: z.ZodObject<any>;
export declare const adminBusinessSponsoredPlacementActionRequestSchema: z.ZodObject<any>;
export declare const adminBusinessProfileActionRequestSchema: z.ZodObject<any>;
export type BusinessProfileType = z.infer<typeof businessProfileTypeSchema>;
export type BusinessProfileStatus = z.infer<typeof businessProfileStatusSchema>;
export type BusinessProfileMemberRole = z.infer<typeof businessProfileMemberRoleSchema>;
export type BusinessProfileInvitationStatus = z.infer<typeof businessProfileInvitationStatusSchema>;
export type BusinessSponsoredPlacementSurface = z.infer<typeof businessSponsoredPlacementSurfaceSchema>;
export type BusinessSponsoredPlacementTargetType = z.infer<typeof businessSponsoredPlacementTargetTypeSchema>;
export type BusinessSponsoredPlacementStatus = z.infer<typeof businessSponsoredPlacementStatusSchema>;
export type BusinessCampaignOpportunityType = z.infer<typeof businessCampaignOpportunityTypeSchema>;
export type BusinessCampaignStatus = z.infer<typeof businessCampaignStatusSchema>;
export type BusinessCampaignItemTargetType = z.infer<typeof businessCampaignItemTargetTypeSchema>;
export type BusinessCampaignApplicationStatus = z.infer<typeof businessCampaignApplicationStatusSchema>;
export type BusinessBudgetStatus = z.infer<typeof businessBudgetStatusSchema>;
export type BusinessBudgetLedgerEntryType = z.infer<typeof businessBudgetLedgerEntryTypeSchema>;
export type CreateBusinessProfileRequest = z.infer<typeof createBusinessProfileRequestSchema>;
export type UpdateBusinessProfileRequest = z.infer<typeof updateBusinessProfileRequestSchema>;
export type RequestBusinessReviewRequest = z.infer<typeof requestBusinessReviewRequestSchema>;
export type BusinessProviderOnboardingLinkRequest = z.infer<typeof businessProviderOnboardingLinkRequestSchema>;
export type BusinessInviteMemberRequest = z.infer<typeof businessInviteMemberRequestSchema>;
export type BusinessUpdateMemberRequest = z.infer<typeof businessUpdateMemberRequestSchema>;
export type BusinessRemoveMemberRequest = z.infer<typeof businessRemoveMemberRequestSchema>;
export type BusinessInvitationActionRequest = z.infer<typeof businessInvitationActionRequestSchema>;
export type BusinessAcceptInvitationRequest = z.infer<typeof businessAcceptInvitationRequestSchema>;
export type BusinessCreateInventoryTemplateRequest = z.infer<typeof businessCreateInventoryTemplateRequestSchema>;
export type BusinessUpdateInventoryTemplateRequest = z.infer<typeof businessUpdateInventoryTemplateRequestSchema>;
export type BusinessListInventoryTemplatesQuery = z.infer<typeof businessListInventoryTemplatesQuerySchema>;
export type BusinessInventoryTemplateReviewRequest = z.infer<typeof businessInventoryTemplateReviewRequestSchema>;
export type BusinessInventoryTemplateArchiveRequest = z.infer<typeof businessInventoryTemplateArchiveRequestSchema>;
export type BusinessCreateNeedRequest = z.infer<typeof businessCreateNeedRequestSchema>;
export type BusinessCreateOfferRequest = z.infer<typeof businessCreateOfferRequestSchema>;
export type BusinessUpdateNeedRequest = z.infer<typeof businessUpdateNeedRequestSchema>;
export type BusinessUpdateOfferRequest = z.infer<typeof businessUpdateOfferRequestSchema>;
export type BusinessListOwnedInventoryQuery = z.infer<typeof businessListOwnedInventoryQuerySchema>;
export type BusinessOwnedInventoryReviewRequest = z.infer<typeof businessOwnedInventoryReviewRequestSchema>;
export type BusinessOwnedInventoryArchiveRequest = z.infer<typeof businessOwnedInventoryArchiveRequestSchema>;
export type BusinessSponsoredPlacementListQuery = z.infer<typeof businessSponsoredPlacementListQuerySchema>;
export type BusinessCreateSponsoredPlacementRequest = z.infer<typeof businessCreateSponsoredPlacementRequestSchema>;
export type BusinessUpdateSponsoredPlacementRequest = z.infer<typeof businessUpdateSponsoredPlacementRequestSchema>;
export type BusinessSponsoredPlacementReviewRequest = z.infer<typeof businessSponsoredPlacementReviewRequestSchema>;
export type BusinessSponsoredPlacementArchiveRequest = z.infer<typeof businessSponsoredPlacementArchiveRequestSchema>;
export type BusinessCampaignListQuery = z.infer<typeof businessCampaignListQuerySchema>;
export type BusinessCreateCampaignRequest = z.infer<typeof businessCreateCampaignRequestSchema>;
export type BusinessUpdateCampaignRequest = z.infer<typeof businessUpdateCampaignRequestSchema>;
export type BusinessCampaignReviewRequest = z.infer<typeof businessCampaignReviewRequestSchema>;
export type BusinessCampaignArchiveRequest = z.infer<typeof businessCampaignArchiveRequestSchema>;
export type BusinessCreateCampaignItemRequest = z.infer<typeof businessCreateCampaignItemRequestSchema>;
export type BusinessUpdateCampaignItemRequest = z.infer<typeof businessUpdateCampaignItemRequestSchema>;
export type BusinessCampaignItemActionRequest = z.infer<typeof businessCampaignItemActionRequestSchema>;
export type BusinessBudgetListQuery = z.infer<typeof businessBudgetListQuerySchema>;
export type BusinessCreateBudgetRequest = z.infer<typeof businessCreateBudgetRequestSchema>;
export type BusinessUpdateBudgetRequest = z.infer<typeof businessUpdateBudgetRequestSchema>;
export type BusinessBudgetReviewRequest = z.infer<typeof businessBudgetReviewRequestSchema>;
export type BusinessBudgetArchiveRequest = z.infer<typeof businessBudgetArchiveRequestSchema>;
export type AdminBusinessCampaignListQuery = z.infer<typeof adminBusinessCampaignListQuerySchema>;
export type AdminBusinessCampaignActionRequest = z.infer<typeof adminBusinessCampaignActionRequestSchema>;
export type AdminBusinessBudgetListQuery = z.infer<typeof adminBusinessBudgetListQuerySchema>;
export type AdminBusinessBudgetActionRequest = z.infer<typeof adminBusinessBudgetActionRequestSchema>;
export type AdminBusinessSponsoredPlacementListQuery = z.infer<typeof adminBusinessSponsoredPlacementListQuerySchema>;
export type AdminBusinessSponsoredPlacementActionRequest = z.infer<typeof adminBusinessSponsoredPlacementActionRequestSchema>;
export type AdminBusinessProfileActionRequest = z.infer<typeof adminBusinessProfileActionRequestSchema>;
//# sourceMappingURL=business.d.ts.map
