import { z } from 'zod';
export declare const publicProfileSchema: z.ZodObject<{
    displayName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    handle: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    bio: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    avatarUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    countryCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, z.core.$strip>;
export declare const publicUserProfileSchema: z.ZodObject<{
    id: z.ZodString;
    memberSince: z.ZodString;
    profile: z.ZodOptional<z.ZodNullable<z.ZodObject<{
        displayName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        handle: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        bio: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        avatarUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        countryCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    }, z.core.$strip>>>;
}, z.core.$strip>;
export declare const publicProfileTradeSummarySchema: z.ZodObject<{
    id: z.ZodString;
    ownerId: z.ZodString;
    providerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    needId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    offerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    title: z.ZodString;
    description: z.ZodString;
    amountCents: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    currency: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    postType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
        need_offer: "need_offer";
        open_need: "open_need";
        open_offer: "open_offer";
    }>>>;
    status: z.ZodEnum<{
        active: "active";
        draft: "draft";
        closed: "closed";
        expired: "expired";
        funded: "funded";
        in_progress: "in_progress";
        submitted: "submitted";
        completed: "completed";
        disputed: "disputed";
        cancelled: "cancelled";
    }>;
    isPublic: z.ZodBoolean;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
    expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    closedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    need: z.ZodOptional<z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        ownerId: z.ZodString;
        title: z.ZodString;
        description: z.ZodString;
        itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
            service: "service";
            goods: "goods";
            other: "other";
        }>>>;
        category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        timing: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
            remote: "remote";
            local: "local";
            hybrid: "hybrid";
        }>>>;
        locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
        status: z.ZodEnum<{
            active: "active";
            draft: "draft";
            fulfilled: "fulfilled";
            closed: "closed";
            expired: "expired";
        }>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        media: z.ZodOptional<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                need: "need";
                offer: "offer";
                trade: "trade";
                profile: "profile";
                support_ticket: "support_ticket";
                support_message: "support_message";
                plan: "plan";
                plan_place: "plan_place";
            }>>>;
            entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            url: z.ZodString;
            storageKey: z.ZodString;
            filename: z.ZodString;
            mimeType: z.ZodString;
            sizeBytes: z.ZodNumber;
            status: z.ZodEnum<{
                active: "active";
                flagged: "flagged";
                removed: "removed";
                pending_review: "pending_review";
            }>;
            reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            createdAt: z.ZodString;
            updatedAt: z.ZodOptional<z.ZodString>;
            owner: z.ZodOptional<z.ZodUnknown>;
            reviewer: z.ZodOptional<z.ZodUnknown>;
        }, z.core.$strip>>>;
    }, z.core.$strip>>>;
    offer: z.ZodOptional<z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        ownerId: z.ZodString;
        title: z.ZodString;
        description: z.ZodString;
        itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
            service: "service";
            goods: "goods";
            other: "other";
        }>>>;
        category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        availability: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
            remote: "remote";
            local: "local";
            hybrid: "hybrid";
        }>>>;
        locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        includes: z.ZodOptional<z.ZodArray<z.ZodString>>;
        tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
        status: z.ZodEnum<{
            active: "active";
            draft: "draft";
            closed: "closed";
            expired: "expired";
            accepted: "accepted";
        }>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        media: z.ZodOptional<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                need: "need";
                offer: "offer";
                trade: "trade";
                profile: "profile";
                support_ticket: "support_ticket";
                support_message: "support_message";
                plan: "plan";
                plan_place: "plan_place";
            }>>>;
            entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            url: z.ZodString;
            storageKey: z.ZodString;
            filename: z.ZodString;
            mimeType: z.ZodString;
            sizeBytes: z.ZodNumber;
            status: z.ZodEnum<{
                active: "active";
                flagged: "flagged";
                removed: "removed";
                pending_review: "pending_review";
            }>;
            reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            createdAt: z.ZodString;
            updatedAt: z.ZodOptional<z.ZodString>;
            owner: z.ZodOptional<z.ZodUnknown>;
            reviewer: z.ZodOptional<z.ZodUnknown>;
        }, z.core.$strip>>>;
    }, z.core.$strip>>>;
    media: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        ownerId: z.ZodString;
        entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
            need: "need";
            offer: "offer";
            trade: "trade";
            profile: "profile";
            support_ticket: "support_ticket";
            support_message: "support_message";
            plan: "plan";
            plan_place: "plan_place";
        }>>>;
        entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        url: z.ZodString;
        storageKey: z.ZodString;
        filename: z.ZodString;
        mimeType: z.ZodString;
        sizeBytes: z.ZodNumber;
        status: z.ZodEnum<{
            active: "active";
            flagged: "flagged";
            removed: "removed";
            pending_review: "pending_review";
        }>;
        reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        createdAt: z.ZodString;
        updatedAt: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodUnknown>;
        reviewer: z.ZodOptional<z.ZodUnknown>;
    }, z.core.$strip>>>;
}, z.core.$strip>;
export declare const publicProfileStatsSchema: z.ZodObject<{
    completedTradesCount: z.ZodNumber;
    activeTradesCount: z.ZodNumber;
    openNeedsCount: z.ZodNumber;
    openOffersCount: z.ZodNumber;
}, z.core.$strip>;
export declare const publicProfileSectionsSchema: z.ZodObject<{
    activeTrades: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        ownerId: z.ZodString;
        providerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        needId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        offerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        title: z.ZodString;
        description: z.ZodString;
        amountCents: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
        currency: z.ZodDefault<z.ZodOptional<z.ZodString>>;
        postType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
            need_offer: "need_offer";
            open_need: "open_need";
            open_offer: "open_offer";
        }>>>;
        status: z.ZodEnum<{
            active: "active";
            draft: "draft";
            closed: "closed";
            expired: "expired";
            funded: "funded";
            in_progress: "in_progress";
            submitted: "submitted";
            completed: "completed";
            disputed: "disputed";
            cancelled: "cancelled";
        }>;
        isPublic: z.ZodBoolean;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        closedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        need: z.ZodOptional<z.ZodNullable<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            title: z.ZodString;
            description: z.ZodString;
            itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                service: "service";
                goods: "goods";
                other: "other";
            }>>>;
            category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            timing: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                remote: "remote";
                local: "local";
                hybrid: "hybrid";
            }>>>;
            locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
            status: z.ZodEnum<{
                active: "active";
                draft: "draft";
                fulfilled: "fulfilled";
                closed: "closed";
                expired: "expired";
            }>;
            createdAt: z.ZodString;
            updatedAt: z.ZodString;
            expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    need: "need";
                    offer: "offer";
                    trade: "trade";
                    profile: "profile";
                    support_ticket: "support_ticket";
                    support_message: "support_message";
                    plan: "plan";
                    plan_place: "plan_place";
                }>>>;
                entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                url: z.ZodString;
                storageKey: z.ZodString;
                filename: z.ZodString;
                mimeType: z.ZodString;
                sizeBytes: z.ZodNumber;
                status: z.ZodEnum<{
                    active: "active";
                    flagged: "flagged";
                    removed: "removed";
                    pending_review: "pending_review";
                }>;
                reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                createdAt: z.ZodString;
                updatedAt: z.ZodOptional<z.ZodString>;
                owner: z.ZodOptional<z.ZodUnknown>;
                reviewer: z.ZodOptional<z.ZodUnknown>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>>;
        offer: z.ZodOptional<z.ZodNullable<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            title: z.ZodString;
            description: z.ZodString;
            itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                service: "service";
                goods: "goods";
                other: "other";
            }>>>;
            category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            availability: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                remote: "remote";
                local: "local";
                hybrid: "hybrid";
            }>>>;
            locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            includes: z.ZodOptional<z.ZodArray<z.ZodString>>;
            tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
            status: z.ZodEnum<{
                active: "active";
                draft: "draft";
                closed: "closed";
                expired: "expired";
                accepted: "accepted";
            }>;
            createdAt: z.ZodString;
            updatedAt: z.ZodString;
            expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    need: "need";
                    offer: "offer";
                    trade: "trade";
                    profile: "profile";
                    support_ticket: "support_ticket";
                    support_message: "support_message";
                    plan: "plan";
                    plan_place: "plan_place";
                }>>>;
                entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                url: z.ZodString;
                storageKey: z.ZodString;
                filename: z.ZodString;
                mimeType: z.ZodString;
                sizeBytes: z.ZodNumber;
                status: z.ZodEnum<{
                    active: "active";
                    flagged: "flagged";
                    removed: "removed";
                    pending_review: "pending_review";
                }>;
                reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                createdAt: z.ZodString;
                updatedAt: z.ZodOptional<z.ZodString>;
                owner: z.ZodOptional<z.ZodUnknown>;
                reviewer: z.ZodOptional<z.ZodUnknown>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>>;
        media: z.ZodOptional<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                need: "need";
                offer: "offer";
                trade: "trade";
                profile: "profile";
                support_ticket: "support_ticket";
                support_message: "support_message";
                plan: "plan";
                plan_place: "plan_place";
            }>>>;
            entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            url: z.ZodString;
            storageKey: z.ZodString;
            filename: z.ZodString;
            mimeType: z.ZodString;
            sizeBytes: z.ZodNumber;
            status: z.ZodEnum<{
                active: "active";
                flagged: "flagged";
                removed: "removed";
                pending_review: "pending_review";
            }>;
            reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            createdAt: z.ZodString;
            updatedAt: z.ZodOptional<z.ZodString>;
            owner: z.ZodOptional<z.ZodUnknown>;
            reviewer: z.ZodOptional<z.ZodUnknown>;
        }, z.core.$strip>>>;
    }, z.core.$strip>>;
    openNeeds: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        ownerId: z.ZodString;
        providerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        needId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        offerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        title: z.ZodString;
        description: z.ZodString;
        amountCents: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
        currency: z.ZodDefault<z.ZodOptional<z.ZodString>>;
        postType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
            need_offer: "need_offer";
            open_need: "open_need";
            open_offer: "open_offer";
        }>>>;
        status: z.ZodEnum<{
            active: "active";
            draft: "draft";
            closed: "closed";
            expired: "expired";
            funded: "funded";
            in_progress: "in_progress";
            submitted: "submitted";
            completed: "completed";
            disputed: "disputed";
            cancelled: "cancelled";
        }>;
        isPublic: z.ZodBoolean;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        closedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        need: z.ZodOptional<z.ZodNullable<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            title: z.ZodString;
            description: z.ZodString;
            itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                service: "service";
                goods: "goods";
                other: "other";
            }>>>;
            category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            timing: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                remote: "remote";
                local: "local";
                hybrid: "hybrid";
            }>>>;
            locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
            status: z.ZodEnum<{
                active: "active";
                draft: "draft";
                fulfilled: "fulfilled";
                closed: "closed";
                expired: "expired";
            }>;
            createdAt: z.ZodString;
            updatedAt: z.ZodString;
            expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    need: "need";
                    offer: "offer";
                    trade: "trade";
                    profile: "profile";
                    support_ticket: "support_ticket";
                    support_message: "support_message";
                    plan: "plan";
                    plan_place: "plan_place";
                }>>>;
                entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                url: z.ZodString;
                storageKey: z.ZodString;
                filename: z.ZodString;
                mimeType: z.ZodString;
                sizeBytes: z.ZodNumber;
                status: z.ZodEnum<{
                    active: "active";
                    flagged: "flagged";
                    removed: "removed";
                    pending_review: "pending_review";
                }>;
                reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                createdAt: z.ZodString;
                updatedAt: z.ZodOptional<z.ZodString>;
                owner: z.ZodOptional<z.ZodUnknown>;
                reviewer: z.ZodOptional<z.ZodUnknown>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>>;
        offer: z.ZodOptional<z.ZodNullable<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            title: z.ZodString;
            description: z.ZodString;
            itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                service: "service";
                goods: "goods";
                other: "other";
            }>>>;
            category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            availability: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                remote: "remote";
                local: "local";
                hybrid: "hybrid";
            }>>>;
            locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            includes: z.ZodOptional<z.ZodArray<z.ZodString>>;
            tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
            status: z.ZodEnum<{
                active: "active";
                draft: "draft";
                closed: "closed";
                expired: "expired";
                accepted: "accepted";
            }>;
            createdAt: z.ZodString;
            updatedAt: z.ZodString;
            expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    need: "need";
                    offer: "offer";
                    trade: "trade";
                    profile: "profile";
                    support_ticket: "support_ticket";
                    support_message: "support_message";
                    plan: "plan";
                    plan_place: "plan_place";
                }>>>;
                entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                url: z.ZodString;
                storageKey: z.ZodString;
                filename: z.ZodString;
                mimeType: z.ZodString;
                sizeBytes: z.ZodNumber;
                status: z.ZodEnum<{
                    active: "active";
                    flagged: "flagged";
                    removed: "removed";
                    pending_review: "pending_review";
                }>;
                reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                createdAt: z.ZodString;
                updatedAt: z.ZodOptional<z.ZodString>;
                owner: z.ZodOptional<z.ZodUnknown>;
                reviewer: z.ZodOptional<z.ZodUnknown>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>>;
        media: z.ZodOptional<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                need: "need";
                offer: "offer";
                trade: "trade";
                profile: "profile";
                support_ticket: "support_ticket";
                support_message: "support_message";
                plan: "plan";
                plan_place: "plan_place";
            }>>>;
            entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            url: z.ZodString;
            storageKey: z.ZodString;
            filename: z.ZodString;
            mimeType: z.ZodString;
            sizeBytes: z.ZodNumber;
            status: z.ZodEnum<{
                active: "active";
                flagged: "flagged";
                removed: "removed";
                pending_review: "pending_review";
            }>;
            reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            createdAt: z.ZodString;
            updatedAt: z.ZodOptional<z.ZodString>;
            owner: z.ZodOptional<z.ZodUnknown>;
            reviewer: z.ZodOptional<z.ZodUnknown>;
        }, z.core.$strip>>>;
    }, z.core.$strip>>;
    openOffers: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        ownerId: z.ZodString;
        providerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        needId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        offerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        title: z.ZodString;
        description: z.ZodString;
        amountCents: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
        currency: z.ZodDefault<z.ZodOptional<z.ZodString>>;
        postType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
            need_offer: "need_offer";
            open_need: "open_need";
            open_offer: "open_offer";
        }>>>;
        status: z.ZodEnum<{
            active: "active";
            draft: "draft";
            closed: "closed";
            expired: "expired";
            funded: "funded";
            in_progress: "in_progress";
            submitted: "submitted";
            completed: "completed";
            disputed: "disputed";
            cancelled: "cancelled";
        }>;
        isPublic: z.ZodBoolean;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        closedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        need: z.ZodOptional<z.ZodNullable<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            title: z.ZodString;
            description: z.ZodString;
            itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                service: "service";
                goods: "goods";
                other: "other";
            }>>>;
            category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            timing: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                remote: "remote";
                local: "local";
                hybrid: "hybrid";
            }>>>;
            locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
            status: z.ZodEnum<{
                active: "active";
                draft: "draft";
                fulfilled: "fulfilled";
                closed: "closed";
                expired: "expired";
            }>;
            createdAt: z.ZodString;
            updatedAt: z.ZodString;
            expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    need: "need";
                    offer: "offer";
                    trade: "trade";
                    profile: "profile";
                    support_ticket: "support_ticket";
                    support_message: "support_message";
                    plan: "plan";
                    plan_place: "plan_place";
                }>>>;
                entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                url: z.ZodString;
                storageKey: z.ZodString;
                filename: z.ZodString;
                mimeType: z.ZodString;
                sizeBytes: z.ZodNumber;
                status: z.ZodEnum<{
                    active: "active";
                    flagged: "flagged";
                    removed: "removed";
                    pending_review: "pending_review";
                }>;
                reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                createdAt: z.ZodString;
                updatedAt: z.ZodOptional<z.ZodString>;
                owner: z.ZodOptional<z.ZodUnknown>;
                reviewer: z.ZodOptional<z.ZodUnknown>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>>;
        offer: z.ZodOptional<z.ZodNullable<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            title: z.ZodString;
            description: z.ZodString;
            itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                service: "service";
                goods: "goods";
                other: "other";
            }>>>;
            category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            availability: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                remote: "remote";
                local: "local";
                hybrid: "hybrid";
            }>>>;
            locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            includes: z.ZodOptional<z.ZodArray<z.ZodString>>;
            tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
            status: z.ZodEnum<{
                active: "active";
                draft: "draft";
                closed: "closed";
                expired: "expired";
                accepted: "accepted";
            }>;
            createdAt: z.ZodString;
            updatedAt: z.ZodString;
            expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    need: "need";
                    offer: "offer";
                    trade: "trade";
                    profile: "profile";
                    support_ticket: "support_ticket";
                    support_message: "support_message";
                    plan: "plan";
                    plan_place: "plan_place";
                }>>>;
                entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                url: z.ZodString;
                storageKey: z.ZodString;
                filename: z.ZodString;
                mimeType: z.ZodString;
                sizeBytes: z.ZodNumber;
                status: z.ZodEnum<{
                    active: "active";
                    flagged: "flagged";
                    removed: "removed";
                    pending_review: "pending_review";
                }>;
                reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                createdAt: z.ZodString;
                updatedAt: z.ZodOptional<z.ZodString>;
                owner: z.ZodOptional<z.ZodUnknown>;
                reviewer: z.ZodOptional<z.ZodUnknown>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>>;
        media: z.ZodOptional<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                need: "need";
                offer: "offer";
                trade: "trade";
                profile: "profile";
                support_ticket: "support_ticket";
                support_message: "support_message";
                plan: "plan";
                plan_place: "plan_place";
            }>>>;
            entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            url: z.ZodString;
            storageKey: z.ZodString;
            filename: z.ZodString;
            mimeType: z.ZodString;
            sizeBytes: z.ZodNumber;
            status: z.ZodEnum<{
                active: "active";
                flagged: "flagged";
                removed: "removed";
                pending_review: "pending_review";
            }>;
            reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            createdAt: z.ZodString;
            updatedAt: z.ZodOptional<z.ZodString>;
            owner: z.ZodOptional<z.ZodUnknown>;
            reviewer: z.ZodOptional<z.ZodUnknown>;
        }, z.core.$strip>>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export declare const publicProfileResponseSchema: z.ZodObject<{
    user: z.ZodObject<{
        id: z.ZodString;
        memberSince: z.ZodString;
        profile: z.ZodOptional<z.ZodNullable<z.ZodObject<{
            displayName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            handle: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            bio: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            avatarUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            countryCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    stats: z.ZodObject<{
        completedTradesCount: z.ZodNumber;
        activeTradesCount: z.ZodNumber;
        openNeedsCount: z.ZodNumber;
        openOffersCount: z.ZodNumber;
    }, z.core.$strip>;
    sections: z.ZodObject<{
        activeTrades: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            providerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            needId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            offerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            title: z.ZodString;
            description: z.ZodString;
            amountCents: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
            currency: z.ZodDefault<z.ZodOptional<z.ZodString>>;
            postType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                need_offer: "need_offer";
                open_need: "open_need";
                open_offer: "open_offer";
            }>>>;
            status: z.ZodEnum<{
                active: "active";
                draft: "draft";
                closed: "closed";
                expired: "expired";
                funded: "funded";
                in_progress: "in_progress";
                submitted: "submitted";
                completed: "completed";
                disputed: "disputed";
                cancelled: "cancelled";
            }>;
            isPublic: z.ZodBoolean;
            createdAt: z.ZodString;
            updatedAt: z.ZodString;
            expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            closedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            need: z.ZodOptional<z.ZodNullable<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                title: z.ZodString;
                description: z.ZodString;
                itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                    service: "service";
                    goods: "goods";
                    other: "other";
                }>>>;
                category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                timing: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    remote: "remote";
                    local: "local";
                    hybrid: "hybrid";
                }>>>;
                locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
                status: z.ZodEnum<{
                    active: "active";
                    draft: "draft";
                    fulfilled: "fulfilled";
                    closed: "closed";
                    expired: "expired";
                }>;
                createdAt: z.ZodString;
                updatedAt: z.ZodString;
                expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    ownerId: z.ZodString;
                    entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                        need: "need";
                        offer: "offer";
                        trade: "trade";
                        profile: "profile";
                        support_ticket: "support_ticket";
                        support_message: "support_message";
                        plan: "plan";
                        plan_place: "plan_place";
                    }>>>;
                    entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    url: z.ZodString;
                    storageKey: z.ZodString;
                    filename: z.ZodString;
                    mimeType: z.ZodString;
                    sizeBytes: z.ZodNumber;
                    status: z.ZodEnum<{
                        active: "active";
                        flagged: "flagged";
                        removed: "removed";
                        pending_review: "pending_review";
                    }>;
                    reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    createdAt: z.ZodString;
                    updatedAt: z.ZodOptional<z.ZodString>;
                    owner: z.ZodOptional<z.ZodUnknown>;
                    reviewer: z.ZodOptional<z.ZodUnknown>;
                }, z.core.$strip>>>;
            }, z.core.$strip>>>;
            offer: z.ZodOptional<z.ZodNullable<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                title: z.ZodString;
                description: z.ZodString;
                itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                    service: "service";
                    goods: "goods";
                    other: "other";
                }>>>;
                category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                availability: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    remote: "remote";
                    local: "local";
                    hybrid: "hybrid";
                }>>>;
                locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                includes: z.ZodOptional<z.ZodArray<z.ZodString>>;
                tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
                status: z.ZodEnum<{
                    active: "active";
                    draft: "draft";
                    closed: "closed";
                    expired: "expired";
                    accepted: "accepted";
                }>;
                createdAt: z.ZodString;
                updatedAt: z.ZodString;
                expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    ownerId: z.ZodString;
                    entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                        need: "need";
                        offer: "offer";
                        trade: "trade";
                        profile: "profile";
                        support_ticket: "support_ticket";
                        support_message: "support_message";
                        plan: "plan";
                        plan_place: "plan_place";
                    }>>>;
                    entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    url: z.ZodString;
                    storageKey: z.ZodString;
                    filename: z.ZodString;
                    mimeType: z.ZodString;
                    sizeBytes: z.ZodNumber;
                    status: z.ZodEnum<{
                        active: "active";
                        flagged: "flagged";
                        removed: "removed";
                        pending_review: "pending_review";
                    }>;
                    reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    createdAt: z.ZodString;
                    updatedAt: z.ZodOptional<z.ZodString>;
                    owner: z.ZodOptional<z.ZodUnknown>;
                    reviewer: z.ZodOptional<z.ZodUnknown>;
                }, z.core.$strip>>>;
            }, z.core.$strip>>>;
            media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    need: "need";
                    offer: "offer";
                    trade: "trade";
                    profile: "profile";
                    support_ticket: "support_ticket";
                    support_message: "support_message";
                    plan: "plan";
                    plan_place: "plan_place";
                }>>>;
                entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                url: z.ZodString;
                storageKey: z.ZodString;
                filename: z.ZodString;
                mimeType: z.ZodString;
                sizeBytes: z.ZodNumber;
                status: z.ZodEnum<{
                    active: "active";
                    flagged: "flagged";
                    removed: "removed";
                    pending_review: "pending_review";
                }>;
                reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                createdAt: z.ZodString;
                updatedAt: z.ZodOptional<z.ZodString>;
                owner: z.ZodOptional<z.ZodUnknown>;
                reviewer: z.ZodOptional<z.ZodUnknown>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>;
        openNeeds: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            providerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            needId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            offerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            title: z.ZodString;
            description: z.ZodString;
            amountCents: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
            currency: z.ZodDefault<z.ZodOptional<z.ZodString>>;
            postType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                need_offer: "need_offer";
                open_need: "open_need";
                open_offer: "open_offer";
            }>>>;
            status: z.ZodEnum<{
                active: "active";
                draft: "draft";
                closed: "closed";
                expired: "expired";
                funded: "funded";
                in_progress: "in_progress";
                submitted: "submitted";
                completed: "completed";
                disputed: "disputed";
                cancelled: "cancelled";
            }>;
            isPublic: z.ZodBoolean;
            createdAt: z.ZodString;
            updatedAt: z.ZodString;
            expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            closedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            need: z.ZodOptional<z.ZodNullable<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                title: z.ZodString;
                description: z.ZodString;
                itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                    service: "service";
                    goods: "goods";
                    other: "other";
                }>>>;
                category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                timing: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    remote: "remote";
                    local: "local";
                    hybrid: "hybrid";
                }>>>;
                locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
                status: z.ZodEnum<{
                    active: "active";
                    draft: "draft";
                    fulfilled: "fulfilled";
                    closed: "closed";
                    expired: "expired";
                }>;
                createdAt: z.ZodString;
                updatedAt: z.ZodString;
                expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    ownerId: z.ZodString;
                    entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                        need: "need";
                        offer: "offer";
                        trade: "trade";
                        profile: "profile";
                        support_ticket: "support_ticket";
                        support_message: "support_message";
                        plan: "plan";
                        plan_place: "plan_place";
                    }>>>;
                    entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    url: z.ZodString;
                    storageKey: z.ZodString;
                    filename: z.ZodString;
                    mimeType: z.ZodString;
                    sizeBytes: z.ZodNumber;
                    status: z.ZodEnum<{
                        active: "active";
                        flagged: "flagged";
                        removed: "removed";
                        pending_review: "pending_review";
                    }>;
                    reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    createdAt: z.ZodString;
                    updatedAt: z.ZodOptional<z.ZodString>;
                    owner: z.ZodOptional<z.ZodUnknown>;
                    reviewer: z.ZodOptional<z.ZodUnknown>;
                }, z.core.$strip>>>;
            }, z.core.$strip>>>;
            offer: z.ZodOptional<z.ZodNullable<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                title: z.ZodString;
                description: z.ZodString;
                itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                    service: "service";
                    goods: "goods";
                    other: "other";
                }>>>;
                category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                availability: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    remote: "remote";
                    local: "local";
                    hybrid: "hybrid";
                }>>>;
                locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                includes: z.ZodOptional<z.ZodArray<z.ZodString>>;
                tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
                status: z.ZodEnum<{
                    active: "active";
                    draft: "draft";
                    closed: "closed";
                    expired: "expired";
                    accepted: "accepted";
                }>;
                createdAt: z.ZodString;
                updatedAt: z.ZodString;
                expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    ownerId: z.ZodString;
                    entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                        need: "need";
                        offer: "offer";
                        trade: "trade";
                        profile: "profile";
                        support_ticket: "support_ticket";
                        support_message: "support_message";
                        plan: "plan";
                        plan_place: "plan_place";
                    }>>>;
                    entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    url: z.ZodString;
                    storageKey: z.ZodString;
                    filename: z.ZodString;
                    mimeType: z.ZodString;
                    sizeBytes: z.ZodNumber;
                    status: z.ZodEnum<{
                        active: "active";
                        flagged: "flagged";
                        removed: "removed";
                        pending_review: "pending_review";
                    }>;
                    reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    createdAt: z.ZodString;
                    updatedAt: z.ZodOptional<z.ZodString>;
                    owner: z.ZodOptional<z.ZodUnknown>;
                    reviewer: z.ZodOptional<z.ZodUnknown>;
                }, z.core.$strip>>>;
            }, z.core.$strip>>>;
            media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    need: "need";
                    offer: "offer";
                    trade: "trade";
                    profile: "profile";
                    support_ticket: "support_ticket";
                    support_message: "support_message";
                    plan: "plan";
                    plan_place: "plan_place";
                }>>>;
                entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                url: z.ZodString;
                storageKey: z.ZodString;
                filename: z.ZodString;
                mimeType: z.ZodString;
                sizeBytes: z.ZodNumber;
                status: z.ZodEnum<{
                    active: "active";
                    flagged: "flagged";
                    removed: "removed";
                    pending_review: "pending_review";
                }>;
                reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                createdAt: z.ZodString;
                updatedAt: z.ZodOptional<z.ZodString>;
                owner: z.ZodOptional<z.ZodUnknown>;
                reviewer: z.ZodOptional<z.ZodUnknown>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>;
        openOffers: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            ownerId: z.ZodString;
            providerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            needId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            offerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            title: z.ZodString;
            description: z.ZodString;
            amountCents: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
            currency: z.ZodDefault<z.ZodOptional<z.ZodString>>;
            postType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                need_offer: "need_offer";
                open_need: "open_need";
                open_offer: "open_offer";
            }>>>;
            status: z.ZodEnum<{
                active: "active";
                draft: "draft";
                closed: "closed";
                expired: "expired";
                funded: "funded";
                in_progress: "in_progress";
                submitted: "submitted";
                completed: "completed";
                disputed: "disputed";
                cancelled: "cancelled";
            }>;
            isPublic: z.ZodBoolean;
            createdAt: z.ZodString;
            updatedAt: z.ZodString;
            expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            closedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            need: z.ZodOptional<z.ZodNullable<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                title: z.ZodString;
                description: z.ZodString;
                itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                    service: "service";
                    goods: "goods";
                    other: "other";
                }>>>;
                category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                timing: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    remote: "remote";
                    local: "local";
                    hybrid: "hybrid";
                }>>>;
                locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
                status: z.ZodEnum<{
                    active: "active";
                    draft: "draft";
                    fulfilled: "fulfilled";
                    closed: "closed";
                    expired: "expired";
                }>;
                createdAt: z.ZodString;
                updatedAt: z.ZodString;
                expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    ownerId: z.ZodString;
                    entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                        need: "need";
                        offer: "offer";
                        trade: "trade";
                        profile: "profile";
                        support_ticket: "support_ticket";
                        support_message: "support_message";
                        plan: "plan";
                        plan_place: "plan_place";
                    }>>>;
                    entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    url: z.ZodString;
                    storageKey: z.ZodString;
                    filename: z.ZodString;
                    mimeType: z.ZodString;
                    sizeBytes: z.ZodNumber;
                    status: z.ZodEnum<{
                        active: "active";
                        flagged: "flagged";
                        removed: "removed";
                        pending_review: "pending_review";
                    }>;
                    reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    createdAt: z.ZodString;
                    updatedAt: z.ZodOptional<z.ZodString>;
                    owner: z.ZodOptional<z.ZodUnknown>;
                    reviewer: z.ZodOptional<z.ZodUnknown>;
                }, z.core.$strip>>>;
            }, z.core.$strip>>>;
            offer: z.ZodOptional<z.ZodNullable<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                title: z.ZodString;
                description: z.ZodString;
                itemType: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
                    service: "service";
                    goods: "goods";
                    other: "other";
                }>>>;
                category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                availability: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                mode: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    remote: "remote";
                    local: "local";
                    hybrid: "hybrid";
                }>>>;
                locationLabel: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                includes: z.ZodOptional<z.ZodArray<z.ZodString>>;
                tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
                status: z.ZodEnum<{
                    active: "active";
                    draft: "draft";
                    closed: "closed";
                    expired: "expired";
                    accepted: "accepted";
                }>;
                createdAt: z.ZodString;
                updatedAt: z.ZodString;
                expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    ownerId: z.ZodString;
                    entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                        need: "need";
                        offer: "offer";
                        trade: "trade";
                        profile: "profile";
                        support_ticket: "support_ticket";
                        support_message: "support_message";
                        plan: "plan";
                        plan_place: "plan_place";
                    }>>>;
                    entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    url: z.ZodString;
                    storageKey: z.ZodString;
                    filename: z.ZodString;
                    mimeType: z.ZodString;
                    sizeBytes: z.ZodNumber;
                    status: z.ZodEnum<{
                        active: "active";
                        flagged: "flagged";
                        removed: "removed";
                        pending_review: "pending_review";
                    }>;
                    reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                    createdAt: z.ZodString;
                    updatedAt: z.ZodOptional<z.ZodString>;
                    owner: z.ZodOptional<z.ZodUnknown>;
                    reviewer: z.ZodOptional<z.ZodUnknown>;
                }, z.core.$strip>>>;
            }, z.core.$strip>>>;
            media: z.ZodOptional<z.ZodArray<z.ZodObject<{
                id: z.ZodString;
                ownerId: z.ZodString;
                entityType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
                    need: "need";
                    offer: "offer";
                    trade: "trade";
                    profile: "profile";
                    support_ticket: "support_ticket";
                    support_message: "support_message";
                    plan: "plan";
                    plan_place: "plan_place";
                }>>>;
                entityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                url: z.ZodString;
                storageKey: z.ZodString;
                filename: z.ZodString;
                mimeType: z.ZodString;
                sizeBytes: z.ZodNumber;
                status: z.ZodEnum<{
                    active: "active";
                    flagged: "flagged";
                    removed: "removed";
                    pending_review: "pending_review";
                }>;
                reviewNote: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewedAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                reviewerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                createdAt: z.ZodString;
                updatedAt: z.ZodOptional<z.ZodString>;
                owner: z.ZodOptional<z.ZodUnknown>;
                reviewer: z.ZodOptional<z.ZodUnknown>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>;
    }, z.core.$strip>;
    viewerState: z.ZodOptional<z.ZodObject<{
        isBlockedByMe: z.ZodOptional<z.ZodBoolean>;
        isBlockingMe: z.ZodOptional<z.ZodBoolean>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export declare const createUserBlockRequestSchema: z.ZodObject<{
    reason: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const userBlockSchema: z.ZodObject<{
    id: z.ZodString;
    blockerId: z.ZodString;
    blockedId: z.ZodString;
    reason: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
    blocked: z.ZodOptional<z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        memberSince: z.ZodString;
        profile: z.ZodOptional<z.ZodNullable<z.ZodObject<{
            displayName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            handle: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            bio: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            avatarUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            countryCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        }, z.core.$strip>>>;
    }, z.core.$strip>>>;
}, z.core.$loose>;
export declare const userBlockResponseSchema: z.ZodObject<{
    blocked: z.ZodBoolean;
    block: z.ZodOptional<z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        blockerId: z.ZodString;
        blockedId: z.ZodString;
        reason: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        blocked: z.ZodOptional<z.ZodNullable<z.ZodObject<{
            id: z.ZodString;
            memberSince: z.ZodString;
            profile: z.ZodOptional<z.ZodNullable<z.ZodObject<{
                displayName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                handle: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                bio: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                avatarUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                countryCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>>;
    }, z.core.$loose>>>;
}, z.core.$strip>;
export declare const userBlocksResponseSchema: z.ZodObject<{
    blocks: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        blockerId: z.ZodString;
        blockedId: z.ZodString;
        reason: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        blocked: z.ZodOptional<z.ZodNullable<z.ZodObject<{
            id: z.ZodString;
            memberSince: z.ZodString;
            profile: z.ZodOptional<z.ZodNullable<z.ZodObject<{
                displayName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                handle: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                bio: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                avatarUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                countryCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>>;
    }, z.core.$loose>>;
}, z.core.$strip>;
export type PublicProfile = z.infer<typeof publicProfileSchema>;
export type PublicUserProfile = z.infer<typeof publicUserProfileSchema>;
export type PublicProfileTradeSummary = z.infer<typeof publicProfileTradeSummarySchema>;
export type PublicProfileStats = z.infer<typeof publicProfileStatsSchema>;
export type PublicProfileSections = z.infer<typeof publicProfileSectionsSchema>;
export type PublicProfileResponse = z.infer<typeof publicProfileResponseSchema>;
export type CreateUserBlockRequest = z.infer<typeof createUserBlockRequestSchema>;
export type UserBlockDto = z.infer<typeof userBlockSchema>;
export type UserBlockResponse = z.infer<typeof userBlockResponseSchema>;
export type UserBlocksResponse = z.infer<typeof userBlocksResponseSchema>;
//# sourceMappingURL=users.d.ts.map