import { Router } from 'express';
import { accountRoutes } from './modules/account/account.routes.js';
import { agendaRoutes } from './modules/agenda/agenda.routes.js';
import { aiAssistRoutes } from './modules/ai/aiAssist.routes.js';
import { adminRoutes } from './modules/admin/admin.routes.js';
import { authRoutes } from './modules/auth/auth.routes.js';
import { businessRoutes } from './modules/business/business.routes.js';
import { creditsRoutes } from './modules/credits/credits.routes.js';
import { healthRoutes } from './modules/health/health.routes.js';
import { inventoryTemplatesRoutes } from './modules/inventory-templates/inventoryTemplates.routes.js';
import { inventoryFoldersRoutes } from './modules/inventory-folders.routes.js';
import { needsRoutes } from './modules/needs/needs.routes.js';
import { notificationsRoutes } from './modules/notifications/notifications.routes.js';
import { mediaRoutes } from './modules/media/media.routes.js';
import { offersRoutes } from './modules/offers/offers.routes.js';
import { profileRoutes } from './modules/profile/profile.routes.js';
import { reportsRoutes } from './modules/reports/reports.routes.js';
import { savedRoutes } from './modules/saved/saved.routes.js';
import { proposalsRoutes } from './modules/proposals/proposals.routes.js';
import { plansRoutes } from './modules/plans/plans.routes.js';
import { plusRoutes } from './modules/subscriptions/plus.routes.js';
import { settingsRoutes } from './modules/settings/settings.routes.js';
import { supportRoutes } from './modules/support/support.routes.js';
import { subscriptionsRoutes } from './modules/subscriptions/subscriptions.routes.js';
import { tradeSearchRoutes } from './modules/trade-search/tradeSearch.routes.js';
import { tradesRoutes } from './modules/trades/trades.routes.js';
import { usersRoutes } from './modules/users/users.routes.js';
import { usageRoutes } from './modules/usage/usage.routes.js';
import { walletRoutes } from './modules/wallet/wallet.routes.js';
import { requireBusinessAccountsEnabled, requireMoneyFeaturesVisible, requireSubscriptionsEnabled, requireWalletVisible, requirePlansEnabled } from './middleware/featureGates.js';

export const routes = Router();

routes.use('/health', healthRoutes);
routes.use('/ai', aiAssistRoutes);
routes.use('/inventory-templates', inventoryTemplatesRoutes);
routes.use('/inventory-folders', inventoryFoldersRoutes);
routes.use('/auth', authRoutes);
routes.use('/account', accountRoutes);
routes.use('/agenda', agendaRoutes);
routes.use('/business', requireBusinessAccountsEnabled(), businessRoutes);
routes.use('/credits', requireMoneyFeaturesVisible('Credit purchase features'), creditsRoutes);
routes.use('/profile', profileRoutes);
routes.use('/reports', reportsRoutes);
routes.use('/saved', savedRoutes);
routes.use('/settings', settingsRoutes);
routes.use('/support', supportRoutes);
routes.use('/subscriptions', requireSubscriptionsEnabled(), subscriptionsRoutes);
routes.use('/notifications', notificationsRoutes);
routes.use('/needs', needsRoutes);
routes.use('/offers', offersRoutes);
routes.use('/trade-search', tradeSearchRoutes);
routes.use('/trades', tradesRoutes);
routes.use('/plans', requirePlansEnabled(), plansRoutes);
routes.use('/plus', plusRoutes);
routes.use('/users', usersRoutes);
routes.use('/usage', usageRoutes);
routes.use('/proposals', proposalsRoutes);
routes.use('/wallet', requireWalletVisible(), walletRoutes);
routes.use('/media', mediaRoutes);
routes.use('/admin', adminRoutes);
