export const WEB_ONBOARDING_GUIDE_COMPLETED_STORAGE_KEY = 'hellowhen_web_onboarding_guide_completed_v1';
export const WEB_ONBOARDING_GUIDE_COMPLETED_COOKIE = 'hellowhen_web_onboarding_guide_completed';
export const WEB_ONBOARDING_GUIDE_COMPLETED_COOKIE_PREFIX = `${WEB_ONBOARDING_GUIDE_COMPLETED_COOKIE}_`;
export const WEB_TRADE_ONBOARDING_GUIDE_COMPLETED_COOKIE = `${WEB_ONBOARDING_GUIDE_COMPLETED_COOKIE_PREFIX}trade`;
export const WEB_ONBOARDING_GUIDE_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 365;
