import type { MediaAssetDto, NeedDto, OfferDto, TradeDto } from '@hellowhen/contracts';

const now = '2026-05-09T12:00:00.000Z';
const inThreeDays = '2026-05-12T23:59:59.000Z';
const inSixDays = '2026-05-15T23:59:59.000Z';

function demoImage(id: string, ownerId: string, entityType: 'need' | 'offer', entityId: string, label: string, tone: string): MediaAssetDto {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="900" viewBox="0 0 900 900"><defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="${tone}"/><stop offset="1" stop-color="#0f172a"/></linearGradient></defs><rect width="900" height="900" fill="url(#g)"/><circle cx="710" cy="180" r="130" fill="rgba(255,255,255,.16)"/><circle cx="160" cy="730" r="210" fill="rgba(255,255,255,.10)"/><text x="72" y="450" fill="white" font-family="Inter, Arial, sans-serif" font-size="58" font-weight="800" letter-spacing="-2">${label}</text></svg>`;
  return {
    id,
    ownerId,
    entityType,
    entityId,
    url: `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`,
    storageKey: `demo/${id}.svg`,
    filename: `${id}.svg`,
    mimeType: 'image/svg+xml',
    sizeBytes: svg.length,
    status: 'active',
    createdAt: now,
    updatedAt: now,
  };
}

export const mockNeeds: NeedDto[] = [
  {
    id: 'demo-need-1',
    ownerId: 'demo-user-1',
    title: 'Landing page design',
    description: 'I need a clean landing page for a small product launch with hero copy, sections, and a simple CTA.',
    itemType: 'service',
    category: 'Design',
    timing: 'This week',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['design', 'launch'],
    status: 'active',
    createdAt: now,
    updatedAt: now,
    expiresAt: inThreeDays,
    media: [],
  },
  {
    id: 'demo-need-2',
    ownerId: 'demo-user-2',
    title: 'Short launch video edit',
    description: 'Looking for someone to polish a 45-second launch video and export it for mobile and social.',
    itemType: 'service',
    category: 'Video',
    timing: '24–48 hours',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['video', 'launch'],
    status: 'active',
    createdAt: now,
    updatedAt: now,
    expiresAt: inSixDays,
    media: [],
  },
  {
    id: 'demo-need-3',
    ownerId: 'demo-user-3',
    title: 'Email launch copy',
    description: 'I need three concise emails for a small product launch: announcement, reminder, and last call.',
    itemType: 'service',
    category: 'Copywriting',
    timing: 'Next week',
    mode: 'remote',
    locationLabel: 'Remote',
    tags: ['copy', 'email'],
    status: 'active',
    createdAt: now,
    updatedAt: now,
    expiresAt: null,
    media: [],
  },
];

export const mockOffers: OfferDto[] = [
  {
    id: 'demo-offer-1',
    ownerId: 'demo-user-1',
    title: 'Product photography',
    description: 'I can shoot and edit a clean set of ecommerce-style product photos for your website or social launch.',
    itemType: 'service',
    category: 'Photography',
    availability: 'Weekend',
    mode: 'local',
    locationLabel: 'Local',
    includes: ['10 edited shots', 'One revision'],
    tags: ['photos', 'ecommerce'],
    status: 'active',
    createdAt: now,
    updatedAt: now,
    expiresAt: null,
    media: [],
  },
  {
    id: 'demo-offer-3',
    ownerId: 'demo-user-3',
    title: 'SEO audit',
    description: 'I can review one site and send a prioritized SEO checklist with technical and content quick wins.',
    itemType: 'service',
    category: 'Marketing',
    availability: 'This month',
    mode: 'remote',
    locationLabel: 'Remote',
    includes: ['One site review', 'Priority checklist'],
    tags: ['seo', 'audit'],
    status: 'active',
    createdAt: now,
    updatedAt: now,
    expiresAt: null,
    media: [],
  },
];

const needLandingMedia = [demoImage('demo-media-need-landing-1', 'demo-user-1', 'need', 'demo-need-1', 'Landing page', '#2563eb')];
const offerPhotoMedia = [
  demoImage('demo-media-offer-photo-1', 'demo-user-1', 'offer', 'demo-offer-1', 'Product photo', '#16a34a'),
  demoImage('demo-media-offer-photo-2', 'demo-user-1', 'offer', 'demo-offer-1', 'Clean shots', '#0f766e'),
];
const needVideoMedia = [demoImage('demo-media-need-video-1', 'demo-user-2', 'need', 'demo-need-2', 'Launch video', '#7c3aed')];
const needCopyMedia = [demoImage('demo-media-need-copy-1', 'demo-user-3', 'need', 'demo-need-3', 'Email copy', '#ea580c')];
const offerAuditMedia = [demoImage('demo-media-offer-audit-1', 'demo-user-3', 'offer', 'demo-offer-3', 'SEO audit', '#0891b2')];

mockNeeds[0]!.media = needLandingMedia;
mockNeeds[1]!.media = needVideoMedia;
mockNeeds[2]!.media = needCopyMedia;
mockOffers[0]!.media = offerPhotoMedia;
mockOffers[1]!.media = offerAuditMedia;

export const mockTrades: TradeDto[] = [
  {
    id: 'demo-trade-1',
    ownerId: 'demo-user-1',
    title: 'Landing page design ↔ Product photography',
    description: 'A service-for-service trade: I need a clean landing page design and I offer product photography for launch assets.',
    creditAmount: 0,
    amountCents: 0,
    currency: 'eur',
    status: 'active',
    isPublic: true,
    createdAt: now,
    updatedAt: now,
    expiresAt: inThreeDays,
    owner: { id: 'demo-user-1', profile: { displayName: 'Mina', handle: 'mina', avatarUrl: null } },
    need: {
      id: 'demo-need-1',
      ownerId: 'demo-user-1',
      title: 'Landing page design',
      description: 'I need a clean landing page for a small product launch with hero copy, sections, and a simple CTA.',
      itemType: 'service',
      category: 'Design',
      timing: 'This week',
      mode: 'remote',
      locationLabel: 'Remote',
      tags: ['design', 'launch'],
      status: 'active',
      createdAt: now,
      updatedAt: now,
      expiresAt: inThreeDays,
      media: needLandingMedia,
    },
    offer: {
      id: 'demo-offer-1',
      ownerId: 'demo-user-1',
      title: 'Product photography',
      description: 'I can shoot and edit a clean set of ecommerce-style product photos for your website or social launch.',
      itemType: 'service',
      category: 'Photography',
      availability: 'Weekend',
      mode: 'local',
      locationLabel: 'Local',
      includes: ['10 edited shots', 'One revision'],
      tags: ['photos', 'ecommerce'],
      status: 'active',
      createdAt: now,
      updatedAt: now,
      expiresAt: null,
      media: offerPhotoMedia,
    },
  },
  {
    id: 'demo-trade-2',
    ownerId: 'demo-user-2',
    title: 'Short launch video edit ↔ Product samples',
    description: 'I need help polishing a short launch video and I offer product samples for content testing.',
    creditAmount: 0,
    amountCents: 0,
    currency: 'eur',
    status: 'active',
    isPublic: true,
    createdAt: now,
    updatedAt: now,
    expiresAt: inSixDays,
    owner: { id: 'demo-user-2', profile: { displayName: 'Noah', handle: 'noah', avatarUrl: null } },
    need: {
      id: 'demo-need-2',
      ownerId: 'demo-user-2',
      title: 'Short launch video edit',
      description: 'Looking for someone to polish a 45-second launch video and export it for mobile and social.',
      itemType: 'service',
      category: 'Video',
      timing: '24–48 hours',
      mode: 'remote',
      locationLabel: 'Remote',
      tags: ['video', 'launch'],
      status: 'active',
      createdAt: now,
      updatedAt: now,
      expiresAt: inSixDays,
      media: needVideoMedia,
    },
    offer: {
      id: 'demo-offer-2',
      ownerId: 'demo-user-2',
      title: 'Product samples',
      description: 'I can send small product samples for content testing or styling reference.',
      itemType: 'goods',
      category: 'Goods',
      availability: 'This week',
      mode: 'local',
      locationLabel: 'Local pickup',
      includes: ['Sample pack', 'Pickup details after acceptance'],
      tags: ['samples', 'goods'],
      status: 'active',
      createdAt: now,
      updatedAt: now,
      expiresAt: null,
      media: [],
    },
  },
  {
    id: 'demo-trade-3',
    ownerId: 'demo-user-3',
    title: 'Email launch copy ↔ SEO audit',
    description: 'I need a short launch email sequence. I can offer a focused SEO audit with quick wins and a simple action list.',
    creditAmount: 0,
    amountCents: 0,
    currency: 'eur',
    status: 'active',
    isPublic: true,
    createdAt: now,
    updatedAt: now,
    expiresAt: null,
    owner: { id: 'demo-user-3', profile: { displayName: 'Sara', handle: 'sara', avatarUrl: null } },
    need: {
      id: 'demo-need-3',
      ownerId: 'demo-user-3',
      title: 'Email launch copy',
      description: 'I need three concise emails for a small product launch: announcement, reminder, and last call.',
      itemType: 'service',
      category: 'Copywriting',
      timing: 'Next week',
      mode: 'remote',
      locationLabel: 'Remote',
      tags: ['copy', 'email'],
      status: 'active',
      createdAt: now,
      updatedAt: now,
      expiresAt: null,
      media: needCopyMedia,
    },
    offer: {
      id: 'demo-offer-3',
      ownerId: 'demo-user-3',
      title: 'SEO audit',
      description: 'I can review one site and send a prioritized SEO checklist with technical and content quick wins.',
      itemType: 'service',
      category: 'Marketing',
      availability: 'This month',
      mode: 'remote',
      locationLabel: 'Remote',
      includes: ['One site review', 'Priority checklist'],
      tags: ['seo', 'audit'],
      status: 'active',
      createdAt: now,
      updatedAt: now,
      expiresAt: null,
      media: offerAuditMedia,
    },
  },
];
